#!/usr/bin/env python3
"""Parse a Next Episode export into staging SQL for the TVBF import.

Stdlib only -- runs on the host python3, no venv and no container needed.
Reads the export and emits SQL that loads the raw rows into an `import_ne`
staging schema. Everything after this step (matching, review, apply) is SQL,
which keeps the whole pipeline inspectable in psql between stages.

The export arrives as an email body: JSON with an SES open-tracking pixel
appended, which is why it lands on disk named `.json.html`. Everything after
the final `}` is discarded.

Usage:
    ./parse_export.py <export-file> > staging.sql
"""

import json
import re
import sys

YEAR_RE = re.compile(r"\s*\((\d{4})\)\s*$")
COUNTRY_RE = re.compile(r"\s*\((?:US|UK|AU|CA|NZ)\)\s*$", re.IGNORECASE)
MARK_RE = re.compile(r"^(\d+)x(.+)$")


def load_export(path: str) -> dict:
    """Read the export, discarding the tracking pixel glued to the end."""
    with open(path, encoding="utf-8") as fh:
        raw = fh.read()
    end = raw.rfind("}")
    if end == -1:
        sys.exit(f"{path}: no JSON object found")
    return json.loads(raw[: end + 1])


def normalize(title: str) -> tuple[str, int | None]:
    """Strip Next Episode's disambiguating suffixes off a title.

    Returns the bare title plus the year when the export supplied one. The
    year is retained as a match constraint rather than discarded -- it is the
    only thing separating the four catalog rows named "Friends".
    """
    year = None
    match = YEAR_RE.search(title)
    base = title
    if match:
        year = int(match.group(1))
        base = YEAR_RE.sub("", base)
    base = COUNTRY_RE.sub("", base)
    return base.strip(), year


def parse_mark(raw: str) -> tuple[int, int | None] | None:
    """Parse a "9x11" watch mark into (season, episode).

    Returns None if the mark is not in SxE shape at all. Returns a null
    episode number for unnumbered specials ("48xSpecial"), which carry a
    season but nothing that identifies an episode -- roughly 6% of this
    export. Those cannot be resolved deterministically; match.sql reports
    them rather than guessing.
    """
    match = MARK_RE.match(raw)
    if not match:
        return None
    season = int(match.group(1))
    tail = match.group(2)
    return (season, int(tail)) if tail.isdigit() else (season, None)


def q(value: str | None) -> str:
    """Quote a value as a SQL string literal."""
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def n(value: int | None) -> str:
    """Render an optional integer as a SQL literal."""
    return "NULL" if value is None else str(int(value))


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)

    export = load_export(sys.argv[1])
    series = export.get("series", [])

    rows = []
    marks = []
    unparseable = []
    for entry in series:
        title = entry["name"]
        base, year = normalize(title)
        rows.append((title, base, year))
        for raw in entry.get("episodes", []):
            parsed = parse_mark(raw)
            if parsed is None:
                unparseable.append((title, raw))
                continue
            season, number = parsed
            marks.append((title, raw, season, number))

    out = sys.stdout.write
    out("-- Generated by parse_export.py. Do not edit by hand.\n")
    out(f"-- source: {sys.argv[1]}\n")
    out(f"-- series: {len(rows)}  marks: {len(marks)}  unparseable: {len(unparseable)}\n\n")
    out("DROP SCHEMA IF EXISTS import_ne CASCADE;\n")
    out("CREATE SCHEMA import_ne;\n\n")

    out("CREATE TABLE import_ne.series (\n")
    out("  title text PRIMARY KEY,\n")
    out("  base  text NOT NULL,\n")
    out("  year  int\n")
    out(");\n")
    out("INSERT INTO import_ne.series (title, base, year) VALUES\n")
    out(",\n".join(f"  ({q(t)}, {q(b)}, {n(y)})" for t, b, y in rows))
    out(";\n\n")

    out("CREATE TABLE import_ne.episode_mark (\n")
    out("  title  text NOT NULL REFERENCES import_ne.series(title),\n")
    out("  raw    text NOT NULL,\n")
    out("  season int  NOT NULL,\n")
    out("  number int\n")
    out(");\n")
    if marks:
        out("INSERT INTO import_ne.episode_mark (title, raw, season, number) VALUES\n")
        out(",\n".join(f"  ({q(t)}, {q(r)}, {s}, {n(e)})" for t, r, s, e in marks))
        out(";\n\n")

    if unparseable:
        out("-- marks that were not in SxE shape at all and were dropped:\n")
        for title, raw in unparseable:
            out(f"--   {title}: {raw}\n")
        out("\n")

    # Movies are intentionally absent: TVBF tracks television only.
    movies = len(export.get("movies", []))
    out(f"-- {movies} movie entries ignored (TVBF is TV-only).\n")


if __name__ == "__main__":
    main()
