"""The daily id export — TMDB's answer to `/updates/shows` (NEU-1034).

It is a static file rather than an endpoint, and the three things that follow
from that are what these tests pin: it costs no rate budget and no credential,
today's file may not exist yet, and an export that parses to nothing must fail
loudly rather than read as "the catalog is already complete".
"""

import gzip
import json
from datetime import date

import httpx
import pytest
import respx

from tvbf.tmdb.export import (
    ExportEntry,
    TruncatedExportError,
    _assert_download_complete,
    export_url,
    fetch_series_export,
    parse_series_export,
)

BASE = "https://files.tmdb.org/p/exports"


def _gz(*records: dict) -> bytes:
    return gzip.compress("\n".join(json.dumps(r) for r in records).encode())


def _ids(entries: list[ExportEntry]) -> list[int]:
    return [e.tmdb_id for e in entries]


# --- the URL ----------------------------------------------------------------


def test_url_uses_tmdbs_zero_padded_month_day_year():
    assert export_url(date(2026, 8, 7)) == f"{BASE}/tv_series_ids_08_07_2026.json.gz"


# --- parsing ----------------------------------------------------------------


def test_parses_one_series_per_line_in_file_order():
    raw = _gz(
        {"id": 1396, "original_name": "Breaking Bad", "popularity": 91.0},
        {"id": 456, "original_name": "The Simpsons", "popularity": 55.5},
    )

    assert parse_series_export(raw) == [
        ExportEntry(tmdb_id=1396, popularity=91.0),
        ExportEntry(tmdb_id=456, popularity=55.5),
    ]


def test_blank_lines_are_ignored():
    raw = gzip.compress(b'{"id": 1}\n\n\n{"id": 2}\n')

    assert _ids(parse_series_export(raw)) == [1, 2]


def test_an_unparseable_line_is_skipped_rather_than_fatal():
    """228k lines of somebody else's file. Losing one series to the delta beats
    losing a three-hour pass."""
    raw = gzip.compress(b'{"id": 1}\nnot json at all\n{"no_id": true}\n{"id": 2}\n')

    assert _ids(parse_series_export(raw)) == [1, 2]


# --- popularity, the second field (NEU-1172) --------------------------------


@pytest.mark.parametrize(
    "record",
    [
        {"id": 5},
        {"id": 5, "popularity": None},
        {"id": 5, "popularity": "3.8"},
        {"id": 5, "popularity": True},
    ],
    ids=["absent", "null", "a string", "a bool"],
)
def test_a_line_whose_popularity_will_not_parse_keeps_its_id(record):
    """The id is what the tombstone reconciler reads absence from, so dropping
    the whole line over its second field would tombstone a series for a
    malformed float. `true` is called out because `bool` is an `int` in Python
    and would otherwise arrive as a popularity of 1.0."""
    assert parse_series_export(_gz(record)) == [ExportEntry(tmdb_id=5, popularity=None)]


def test_an_integer_popularity_is_read_as_a_float():
    assert parse_series_export(_gz({"id": 5, "popularity": 3})) == [
        ExportEntry(tmdb_id=5, popularity=3.0)
    ]


def test_a_truncated_gzip_stream_raises_rather_than_yielding_a_short_list():
    """The failure mode a file has and an endpoint does not (NEU-1036).

    Every gzip member ends in a CRC32 and a length, so decompressing the whole
    member at once cannot get past a cut. Streaming and swallowing the EOF would
    yield a valid but silently short JSONL stream — and the tombstone reconciler
    reads a short export as proof the missing series are gone.
    """
    whole = _gz(*({"id": i} for i in range(1, 500)))

    with pytest.raises(TruncatedExportError, match="did not decompress cleanly"):
        parse_series_export(whole[: len(whole) // 2])


def test_a_body_that_is_not_gzip_at_all_raises():
    """An error page served with a 200 is not a catalog list."""
    with pytest.raises(TruncatedExportError):
        parse_series_export(b"<html>nope</html>")


def test_an_export_with_no_ids_raises():
    """The dangerous silent failure. Nothing downstream can tell an empty work
    list from a fully-ingested catalog, so a truncated file would otherwise
    finalise the run as a success having done nothing."""
    with pytest.raises(ValueError, match="zero series ids"):
        parse_series_export(gzip.compress(b"\n\n"))


# --- fetching ---------------------------------------------------------------


@respx.mock
async def test_fetches_todays_export_when_it_exists():
    respx.get(f"{BASE}/tv_series_ids_08_10_2026.json.gz").mock(
        return_value=httpx.Response(200, content=_gz({"id": 7}))
    )

    assert await fetch_series_export(today=date(2026, 8, 10)) == [
        ExportEntry(tmdb_id=7, popularity=None)
    ]


@respx.mock
@pytest.mark.parametrize("not_published", [403, 404])
async def test_falls_back_to_the_previous_day(not_published):
    """ "Regenerated by 08:00 UTC" is a deadline, not a guarantee, and S3 answers
    a missing key with 403 as readily as 404. A run triggered at 07:00 should
    use yesterday's list, not fail."""
    respx.get(f"{BASE}/tv_series_ids_08_10_2026.json.gz").mock(
        return_value=httpx.Response(not_published)
    )
    respx.get(f"{BASE}/tv_series_ids_08_09_2026.json.gz").mock(
        return_value=httpx.Response(200, content=_gz({"id": 7}, {"id": 8}))
    )

    assert _ids(await fetch_series_export(today=date(2026, 8, 10))) == [7, 8]


@respx.mock
async def test_raises_when_nothing_is_published_within_the_lookback():
    respx.get(url__regex=r".*tv_series_ids.*").mock(return_value=httpx.Response(403))

    with pytest.raises(RuntimeError, match="no TMDB id export published"):
        await fetch_series_export(today=date(2026, 8, 10))


@respx.mock
async def test_a_server_error_is_not_mistaken_for_an_unpublished_file():
    """A 5xx means the host is broken, not that the day's file is missing.
    Walking past it would silently ingest against a stale catalog list."""
    respx.get(f"{BASE}/tv_series_ids_08_10_2026.json.gz").mock(return_value=httpx.Response(503))

    with pytest.raises(httpx.HTTPStatusError):
        await fetch_series_export(today=date(2026, 8, 10))


@respx.mock
async def test_a_body_shorter_than_content_length_is_refused():
    """A download that ended early, caught before anything reads it as a catalog."""
    body = _gz({"id": 7})
    respx.get(f"{BASE}/tv_series_ids_08_10_2026.json.gz").mock(
        return_value=httpx.Response(200, content=body, headers={"content-length": "9999"})
    )

    with pytest.raises(TruncatedExportError, match="declared bytes"):
        await fetch_series_export(today=date(2026, 8, 10))


def test_a_content_encoded_body_is_not_mistaken_for_a_short_one():
    """`Content-Length` then describes the wire bytes and `content` the decoded
    ones, so comparing them would refuse every healthy download. Truncation in
    that case is still caught by the gzip trailer."""
    resp = httpx.Response(
        200,
        content=_gz({"id": 7}),
        headers={"content-length": "9999", "content-encoding": "gzip"},
        request=httpx.Request("GET", f"{BASE}/tv_series_ids_08_10_2026.json.gz"),
    )

    _assert_download_complete(resp)  # must not raise


@respx.mock
async def test_the_request_carries_no_credential():
    """Public static host. Sending the bearer token here widens where it can
    leak for nothing in return."""
    respx.get(f"{BASE}/tv_series_ids_08_10_2026.json.gz").mock(
        return_value=httpx.Response(200, content=_gz({"id": 7}))
    )

    await fetch_series_export(today=date(2026, 8, 10))

    assert "Authorization" not in respx.calls.last.request.headers
