"""'drop uq_season_show_number'

Revision ID: 2668ec5f731e
Revises: 8927c889e469
Create Date: 2026-04-19 21:41:18.995003+00:00

"""
from alembic import op

revision = '2668ec5f731e'
down_revision = '8927c889e469'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_season_show_number'), 'season', schema='tvmaze', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_season_show_number'), 'season', ['show_id', 'number'], schema='tvmaze', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
