"""add catalog credit tables (NEU-1038)

Person, per-show character, the interned crew role, show cast, show crew, episode
guest cast and episode crew — the audit's *modeled* credit rows, and the last of
`catalog`'s table definitions. `created_by` is not among them: it is a
show-creator credit TMDB models separately, and `catalog.show_creator` landed
with NEU-1032.

Three things differ from the `tvmaze` originals, each measured rather than
ported (`scripts/probe_tmdb_credit_shapes.py`, 5 series, 2026-08-11):

**One `crew_role`, not two.** `tvmaze` keeps `crew_role` and `episode_crew_role`
apart because its two vocabularies are disjoint. TMDB emits the same
`department` + `job` pair on both sides and all 78 episode-level pairs also
appear at show level — 100% overlap — so a second lookup would hold a copy of the
same values.

**No ordering column on either crew table.** TMDB sends no `order` on a crew
entry at all: 0 of 2,066 show-crew and 0 of 7,456 episode-crew entries.
`episode_count` is the ordering, which is what NEU-1039 sorts on. Cast and guest
stars do carry `order` and keep it — as `billing_order` and `credit_order`
respectively, the two terms `CONTEXT.md` uses, rather than `tvmaze`'s one
`sort_order` for both grains.

**`character_id` is nullable.** TV Maze always sent a character object; TMDB
sends free text that is occasionally empty (1 blank of 7,629 sampled roles). The
episode guest-cast unique key is therefore `NULLS NOT DISTINCT`, or two
null-character credits for one person on one episode would never conflict and
every re-ingest would add another copy.

Two things here are hand-written rather than autogenerated:

**The folded trigram index on `person.name`.** `/people?search=` folds both the
column and the query token, so the leading-wildcard LIKE needs a GIN trigram
index over the folded expression. It is an expression index, cannot be declared
on the model, and a future `--autogenerate` will propose dropping it — exactly as
it does for the four `catalog` and three `tvmaze` ones (see aa4571de8f17). Strip
that from any migration proposing it.

**Eleven spurious index drops** proposed for that same reason — four in
`catalog`, seven in `tvmaze` — have been removed. This migration creates tables
in `catalog` and touches nothing else.

Revision ID: 76da9dc2c5ed
Revises: e3f16b90c2da
Create Date: 2026-08-11 04:07:36.531182+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "76da9dc2c5ed"
down_revision: str | Sequence[str] | None = "e3f16b90c2da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The folded form `sql_fold.folded` builds in SQL. Kept as one string so the
# index and the query cannot drift apart into a silent table scan.
_FOLDED = "immutable_unaccent(lower(regexp_replace({col}, '[[:punct:][:space:]]+', '', 'g')))"


def upgrade() -> None:
    op.create_table(
        "person",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("original_name", sa.Text(), nullable=True),
        sa.Column("gender", sa.Integer(), nullable=True),
        sa.Column("known_for_department", sa.Text(), nullable=True),
        sa.Column("popularity", sa.Double(), nullable=True),
        sa.Column("profile_path", sa.Text(), nullable=True),
        sa.Column("adult", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tmdb_id", name="uq_person_tmdb_id"),
        schema="catalog",
    )
    op.create_table(
        "character",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        # The interning key. `(show_id, name)` replaces TV Maze's global
        # character id: TMDB has no character entity, so there is nothing
        # upstream to key on.
        sa.UniqueConstraint("show_id", "name", name="uq_character_show_name"),
        schema="catalog",
    )
    op.create_table(
        "crew_role",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        sa.Column("department", sa.Text(), nullable=False),
        sa.Column("job", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("department", "job", name="uq_crew_role_department_job"),
        schema="catalog",
    )
    op.create_table(
        "show_cast",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("person_id", sa.BigInteger(), nullable=False),
        sa.Column("character_id", sa.BigInteger(), nullable=True),
        sa.Column("credit_id", sa.Text(), nullable=True),
        sa.Column("episode_count", sa.Integer(), nullable=True),
        sa.Column("total_episode_count", sa.Integer(), nullable=True),
        sa.Column("billing_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["character_id"], ["catalog.character.id"]),
        sa.ForeignKeyConstraint(["person_id"], ["catalog.person.id"]),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        # No UNIQUE (show_id, person_id, character_id), carried forward from
        # tvmaze.show_cast: refresh is delete-then-insert so there is nothing to
        # conflict on, and a uniqueness assumption over upstream data is what
        # broke ingestion on tvmaze.season.
        schema="catalog",
    )
    op.create_index(
        "ix_show_cast_show_id_episode_count",
        "show_cast",
        ["show_id", "episode_count"],
        unique=False,
        schema="catalog",
    )
    op.create_index(
        "ix_show_cast_person_id", "show_cast", ["person_id"], unique=False, schema="catalog"
    )
    op.create_table(
        "show_crew",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("person_id", sa.BigInteger(), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.Column("credit_id", sa.Text(), nullable=True),
        sa.Column("episode_count", sa.Integer(), nullable=True),
        sa.Column("total_episode_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["person_id"], ["catalog.person.id"]),
        sa.ForeignKeyConstraint(["role_id"], ["catalog.crew_role.id"]),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="catalog",
    )
    op.create_index(
        "ix_show_crew_show_id_episode_count",
        "show_crew",
        ["show_id", "episode_count"],
        unique=False,
        schema="catalog",
    )
    op.create_index(
        "ix_show_crew_person_id", "show_crew", ["person_id"], unique=False, schema="catalog"
    )
    op.create_table(
        "episode_guest_cast",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        sa.Column("episode_id", sa.BigInteger(), nullable=False),
        sa.Column("person_id", sa.BigInteger(), nullable=False),
        sa.Column("character_id", sa.BigInteger(), nullable=True),
        sa.Column("credit_id", sa.Text(), nullable=True),
        sa.Column("credit_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["character_id"], ["catalog.character.id"]),
        sa.ForeignKeyConstraint(["episode_id"], ["catalog.episode.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["person_id"], ["catalog.person.id"]),
        sa.PrimaryKeyConstraint("id"),
        # Three-part, carried forward: one character is played by more than one
        # person on 17 of 1,043 sampled episodes, so (episode_id, character_id)
        # would silently drop rows. NULLS NOT DISTINCT because character_id is
        # nullable here — see the module docstring.
        sa.UniqueConstraint(
            "episode_id",
            "person_id",
            "character_id",
            name="uq_egc_episode_person_character",
            postgresql_nulls_not_distinct=True,
        ),
        schema="catalog",
    )
    op.create_index(
        "ix_egc_person_id", "episode_guest_cast", ["person_id"], unique=False, schema="catalog"
    )
    op.create_table(
        "episode_crew",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        sa.Column("episode_id", sa.BigInteger(), nullable=False),
        sa.Column("person_id", sa.BigInteger(), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.Column("credit_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["episode_id"], ["catalog.episode.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["person_id"], ["catalog.person.id"]),
        sa.ForeignKeyConstraint(["role_id"], ["catalog.crew_role.id"]),
        sa.PrimaryKeyConstraint("id"),
        # Three-part for the same reason: one person holds more than one crew
        # role on 36 of 1,043 sampled episodes.
        sa.UniqueConstraint(
            "episode_id", "person_id", "role_id", name="uq_episode_crew_episode_person_role"
        ),
        schema="catalog",
    )
    op.create_index(
        "ix_episode_crew_person_id", "episode_crew", ["person_id"], unique=False, schema="catalog"
    )

    # Hand-written: an expression index the model cannot declare. Same shape as
    # tvmaze's ix_person_name_folded_trgm (b3f7c1d9a204) — `/people?search=`
    # folds both sides, so the leading-wildcard LIKE needs the GIN trigram index
    # over the folded expression or every keystroke is a seq scan.
    op.execute(
        f"CREATE INDEX ix_person_name_folded_trgm ON catalog.person "
        f"USING gin ({_FOLDED.format(col='name')} gin_trgm_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS catalog.ix_person_name_folded_trgm")
    op.drop_index("ix_episode_crew_person_id", table_name="episode_crew", schema="catalog")
    op.drop_table("episode_crew", schema="catalog")
    op.drop_index("ix_egc_person_id", table_name="episode_guest_cast", schema="catalog")
    op.drop_table("episode_guest_cast", schema="catalog")
    op.drop_index("ix_show_crew_person_id", table_name="show_crew", schema="catalog")
    op.drop_index("ix_show_crew_show_id_episode_count", table_name="show_crew", schema="catalog")
    op.drop_table("show_crew", schema="catalog")
    op.drop_index("ix_show_cast_person_id", table_name="show_cast", schema="catalog")
    op.drop_index("ix_show_cast_show_id_episode_count", table_name="show_cast", schema="catalog")
    op.drop_table("show_cast", schema="catalog")
    op.drop_table("crew_role", schema="catalog")
    op.drop_table("character", schema="catalog")
    op.drop_table("person", schema="catalog")
