"""'initial tvmaze schema'

Revision ID: 8927c889e469
Revises: 
Create Date: 2026-04-19 18:52:53.536020+00:00

"""
import sqlalchemy as sa
from alembic import op

revision = '8927c889e469'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_genre_name'),
    schema='tvmaze'
    )
    op.create_table('ingest_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update_cursor', sa.BigInteger(), nullable=True),
    sa.Column('shows_processed', sa.Integer(), nullable=False),
    sa.Column('shows_failed', sa.Integer(), nullable=False),
    sa.Column('last_progress_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("kind IN ('initial', 'update')", name='ck_ingest_run_kind'),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed', 'cancelled')", name='ck_ingest_run_status'),
    sa.PrimaryKeyConstraint('id'),
    schema='tvmaze'
    )
    op.create_table('network',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('country_code', sa.Text(), nullable=True),
    sa.Column('country_name', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tvmaze'
    )
    op.create_table('web_channel',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('country_code', sa.Text(), nullable=True),
    sa.Column('country_name', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tvmaze'
    )
    op.create_table('show',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('premiered', sa.Date(), nullable=True),
    sa.Column('ended', sa.Date(), nullable=True),
    sa.Column('official_site', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('image_medium', sa.Text(), nullable=True),
    sa.Column('image_original', sa.Text(), nullable=True),
    sa.Column('externals_imdb', sa.Text(), nullable=True),
    sa.Column('externals_tvdb', sa.Integer(), nullable=True),
    sa.Column('externals_tvrage', sa.Integer(), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('web_channel_id', sa.Integer(), nullable=True),
    sa.Column('tvmaze_updated', sa.BigInteger(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['tvmaze.network.id'], ),
    sa.ForeignKeyConstraint(['web_channel_id'], ['tvmaze.web_channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tvmaze'
    )
    op.create_table('season',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('episode_order', sa.Integer(), nullable=True),
    sa.Column('premiere_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('web_channel_id', sa.Integer(), nullable=True),
    sa.Column('image_medium', sa.Text(), nullable=True),
    sa.Column('image_original', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['tvmaze.network.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['tvmaze.show.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['web_channel_id'], ['tvmaze.web_channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('show_id', 'number', name='uq_season_show_number'),
    schema='tvmaze'
    )
    op.create_table('show_genre',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['tvmaze.genre.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['tvmaze.show.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('show_id', 'genre_id', name='pk_show_genre'),
    schema='tvmaze'
    )
    op.create_table('episode',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('airdate', sa.Date(), nullable=True),
    sa.Column('airtime', sa.Time(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('image_medium', sa.Text(), nullable=True),
    sa.Column('image_original', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['tvmaze.season.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['show_id'], ['tvmaze.show.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='tvmaze'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episode', schema='tvmaze')
    op.drop_table('show_genre', schema='tvmaze')
    op.drop_table('season', schema='tvmaze')
    op.drop_table('show', schema='tvmaze')
    op.drop_table('web_channel', schema='tvmaze')
    op.drop_table('network', schema='tvmaze')
    op.drop_table('ingest_run', schema='tvmaze')
    op.drop_table('genre', schema='tvmaze')
    # ### end Alembic commands ###
