"""add tvmaze.rate_budget

The TV Maze request budget, as one token-bucket row every process shares
(ADR-0006). Hand-written rather than autogenerated: autogenerate on this repo
proposes dropping seven production indexes it cannot see in the metadata,
including the GIN trigram index behind AKA search.

Revision ID: 9c31f0a5b7d2
Revises: 77574869e747
Create Date: 2026-08-07

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9c31f0a5b7d2"
down_revision: str | Sequence[str] | None = "77574869e747"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "rate_budget",
        sa.Column("id", sa.SmallInteger(), autoincrement=False, nullable=False),
        sa.Column("tokens", sa.Double(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("id = 1", name="ck_rate_budget_single_row"),
        sa.PrimaryKeyConstraint("id"),
        schema="tvmaze",
    )
    # Seeded full, at the default capacity. The limiter re-caps to whatever
    # `TVMAZE_RATE_LIMIT_REQUESTS` actually says on its first refill, so a
    # deployment on a different budget corrects itself within one window.
    op.execute("INSERT INTO tvmaze.rate_budget (id, tokens) VALUES (1, 18)")


def downgrade() -> None:
    op.drop_table("rate_budget", schema="tvmaze")
