"""add catalog tables for the full TMDB surface (NEU-1032)

The `catalog` schema's tables proper, built to the contract in
`docs/specs/NEU-1031-tmdb-coverage-audit.md`. Scope is TMDB's whole response
surface rather than TV Maze parity — every field the audit classified *modeled*
gets a column, so this is the last time these tables are rewritten. The credit
tables — person, character, crew roles, cast, crew and guest cast — are
NEU-1038's and land separately. `created_by` is *not* among them: it is a
show-creator credit TMDB models separately, so `show_creator` is here.

Three things here are hand-written rather than autogenerated:

**The show <-> episode cycle.** `show.last_episode_to_air_id` and
`next_episode_to_air_id` point at `catalog.episode`, which points back at
`catalog.show`. The models carry `use_alter=True` for it, but autogenerate emits
those constraints inline in `create_table('show')` anyway, where the target table
does not exist yet. They are added after `episode` instead, and dropped before it.

**Four GIN trigram indexes.** They are expression indexes and cannot be declared
on the models, so a future `--autogenerate` will propose dropping them, exactly
as it does for their `tvmaze` counterparts (see 77574869e747). Strip that from
any migration that proposes it — they are what keeps AKA-aware search off a
table scan of the catalog.

**Seven spurious `tvmaze` index drops** proposed by autogenerate for the same
reason have been removed. This migration touches nothing outside `catalog`.

Revision ID: aa4571de8f17
Revises: c9f2b7a41d38
Create Date: 2026-08-09 21:05:16.164596+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "aa4571de8f17"
down_revision: str | Sequence[str] | None = "c9f2b7a41d38"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The folded form `browse_queries._fold` builds in SQL. Kept as one string so
# the index and the query cannot drift apart into a silent table scan.
_FOLDED = "immutable_unaccent(lower(regexp_replace({col}, '[[:punct:][:space:]]+', '', 'g')))"


def upgrade() -> None:
    op.create_table(
        "country",
        sa.Column("iso_3166_1", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("iso_3166_1"),
        schema="catalog",
    )
    op.create_table(
        "genre",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tmdb_id", name="uq_genre_tmdb_id"),
        schema="catalog",
    )
    op.create_table(
        "keyword",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tmdb_id", name="uq_keyword_tmdb_id"),
        schema="catalog",
    )
    op.create_table(
        "language",
        sa.Column("iso_639_1", sa.Text(), nullable=False),
        sa.Column("english_name", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("iso_639_1"),
        schema="catalog",
    )
    op.create_table(
        "network",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("logo_path", sa.Text(), nullable=True),
        sa.Column("origin_country", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tmdb_id", name="uq_network_tmdb_id"),
        schema="catalog",
    )
    op.create_table(
        "production_company",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("logo_path", sa.Text(), nullable=True),
        sa.Column("origin_country", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tmdb_id", name="uq_production_company_tmdb_id"),
        schema="catalog",
    )
    op.create_table(
        "watch_provider",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("logo_path", sa.Text(), nullable=True),
        sa.Column("display_priority", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tmdb_id", name="uq_watch_provider_tmdb_id"),
        schema="catalog",
    )

    # The two FKs to `catalog.episode` are added at the end of this function,
    # once that table exists.
    op.create_table(
        "show",
        sa.Column(
            "id", sa.BigInteger(), sa.Identity(always=False, start=1000000), nullable=False
        ),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("original_name", sa.Text(), nullable=True),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("tagline", sa.Text(), nullable=True),
        sa.Column("homepage", sa.Text(), nullable=True),
        sa.Column("type", sa.Text(), nullable=True),
        sa.Column("adult", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column(
            "is_ended",
            sa.Boolean(),
            sa.Computed("coalesce(status IN ('Ended', 'Canceled'), false)", persisted=True),
            nullable=False,
        ),
        sa.Column("in_production", sa.Boolean(), nullable=True),
        sa.Column("first_air_date", sa.Date(), nullable=True),
        sa.Column("last_air_date", sa.Date(), nullable=True),
        sa.Column("original_language", sa.Text(), nullable=True),
        sa.Column("popularity", sa.Double(), nullable=True),
        sa.Column("vote_average", sa.Numeric(precision=5, scale=3), nullable=True),
        sa.Column("vote_count", sa.Integer(), nullable=True),
        sa.Column("poster_path", sa.Text(), nullable=True),
        sa.Column("backdrop_path", sa.Text(), nullable=True),
        sa.Column("number_of_episodes", sa.Integer(), nullable=True),
        sa.Column("number_of_seasons", sa.Integer(), nullable=True),
        sa.Column("episode_run_time", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("runtime", sa.Integer(), nullable=True),
        sa.Column("last_episode_to_air_id", sa.BigInteger(), nullable=True),
        sa.Column("next_episode_to_air_id", sa.BigInteger(), nullable=True),
        sa.Column("imdb_id", sa.Text(), nullable=True),
        sa.Column("tvdb_id", sa.Integer(), nullable=True),
        sa.Column("tvrage_id", sa.Integer(), nullable=True),
        sa.Column("wikidata_id", sa.Text(), nullable=True),
        sa.Column("freebase_id", sa.Text(), nullable=True),
        sa.Column("freebase_mid", sa.Text(), nullable=True),
        sa.Column("facebook_id", sa.Text(), nullable=True),
        sa.Column("instagram_id", sa.Text(), nullable=True),
        sa.Column("twitter_id", sa.Text(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_upstream_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tmdb_id", name="uq_show_tmdb_id"),
        schema="catalog",
    )
    op.create_index("ix_show_imdb_id", "show", ["imdb_id"], unique=False, schema="catalog")
    op.create_index("ix_show_tvdb_id", "show", ["tvdb_id"], unique=False, schema="catalog")

    op.create_table(
        "show_aka",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("country_code", sa.Text(), nullable=True),
        sa.Column("type", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="catalog",
    )
    op.create_index(
        "ix_show_aka_show_id",
        "show_aka",
        ["show_id"],
        unique=False,
        schema="catalog",
    )
    op.create_table(
        "show_creator",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("tmdb_person_id", sa.Integer(), nullable=True),
        sa.Column("credit_id", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("original_name", sa.Text(), nullable=True),
        sa.Column("gender", sa.Integer(), nullable=True),
        sa.Column("profile_path", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("show_id", "credit_id", name="uq_show_creator_show_credit"),
        schema="catalog",
    )
    op.create_table(
        "content_rating",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("country_code", sa.Text(), nullable=False),
        sa.Column("rating", sa.Text(), nullable=True),
        sa.Column("descriptors", sa.ARRAY(sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["country_code"], ["catalog.country.iso_3166_1"]),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("show_id", "country_code", name="uq_content_rating_show_country"),
        schema="catalog",
    )
    op.create_table(
        "episode_group",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        sa.Column("tmdb_id", sa.Text(), nullable=True),
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("episode_count", sa.Integer(), nullable=True),
        sa.Column("group_count", sa.Integer(), nullable=True),
        sa.Column("type", sa.Integer(), nullable=True),
        sa.Column("network_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["network_id"], ["catalog.network.id"]),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tmdb_id", name="uq_episode_group_tmdb_id"),
        schema="catalog",
    )
    op.create_index(
        "ix_episode_group_show_id", "episode_group", ["show_id"], unique=False, schema="catalog"
    )
    op.create_table(
        "image",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("aspect_ratio", sa.Double(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("language_code", sa.Text(), nullable=True),
        sa.Column("vote_average", sa.Numeric(precision=5, scale=3), nullable=True),
        sa.Column("vote_count", sa.Integer(), nullable=True),
        sa.CheckConstraint("kind IN ('backdrop', 'logo', 'poster')", name="ck_image_kind"),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("show_id", "kind", "file_path", name="uq_image_show_kind_path"),
        schema="catalog",
    )
    op.create_table(
        "season",
        sa.Column(
            "id", sa.BigInteger(), sa.Identity(always=False, start=1000000), nullable=False
        ),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("season_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("poster_path", sa.Text(), nullable=True),
        sa.Column("air_date", sa.Date(), nullable=True),
        sa.Column("vote_average", sa.Numeric(precision=5, scale=3), nullable=True),
        sa.Column("episode_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tmdb_id", name="uq_season_tmdb_id"),
        schema="catalog",
    )
    op.create_index(
        "ix_season_show_id_number",
        "season",
        ["show_id", "season_number"],
        unique=False,
        schema="catalog",
    )
    op.create_table(
        "show_genre",
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("genre_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["genre_id"], ["catalog.genre.id"]),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("show_id", "genre_id", name="pk_show_genre"),
        schema="catalog",
    )
    op.create_index(
        "ix_show_genre_genre_id", "show_genre", ["genre_id"], unique=False, schema="catalog"
    )
    op.create_table(
        "show_keyword",
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("keyword_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["keyword_id"], ["catalog.keyword.id"]),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("show_id", "keyword_id", name="pk_show_keyword"),
        schema="catalog",
    )
    op.create_index(
        "ix_show_keyword_keyword_id", "show_keyword", ["keyword_id"], unique=False, schema="catalog"
    )
    op.create_table(
        "show_language",
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("language_code", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["language_code"], ["catalog.language.iso_639_1"]),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("show_id", "language_code", name="pk_show_language"),
        schema="catalog",
    )
    op.create_table(
        "show_network",
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("network_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["network_id"], ["catalog.network.id"]),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("show_id", "network_id", name="pk_show_network"),
        schema="catalog",
    )
    op.create_index(
        "ix_show_network_network_id", "show_network", ["network_id"], unique=False, schema="catalog"
    )
    op.create_table(
        "show_origin_country",
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("country_code", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["country_code"], ["catalog.country.iso_3166_1"]),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("show_id", "country_code", name="pk_show_origin_country"),
        schema="catalog",
    )
    op.create_table(
        "show_production_company",
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["catalog.production_company.id"]),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("show_id", "company_id", name="pk_show_production_company"),
        schema="catalog",
    )
    op.create_index(
        "ix_show_production_company_company_id",
        "show_production_company",
        ["company_id"],
        unique=False,
        schema="catalog",
    )
    op.create_table(
        "show_production_country",
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("country_code", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["country_code"], ["catalog.country.iso_3166_1"]),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("show_id", "country_code", name="pk_show_production_country"),
        schema="catalog",
    )
    op.create_table(
        "show_spoken_language",
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("language_code", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["language_code"], ["catalog.language.iso_639_1"]),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("show_id", "language_code", name="pk_show_spoken_language"),
        schema="catalog",
    )
    op.create_table(
        "show_watch_provider",
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("country_code", sa.Text(), nullable=False),
        sa.Column("offer_type", sa.Text(), nullable=False),
        sa.Column("provider_id", sa.BigInteger(), nullable=False),
        sa.Column("display_priority", sa.Integer(), nullable=True),
        sa.Column("link", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "offer_type IN ('flatrate', 'buy', 'rent', 'free', 'ads')",
            name="ck_show_watch_provider_offer_type",
        ),
        sa.ForeignKeyConstraint(["country_code"], ["catalog.country.iso_3166_1"]),
        sa.ForeignKeyConstraint(["provider_id"], ["catalog.watch_provider.id"]),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint(
            "show_id", "country_code", "offer_type", "provider_id", name="pk_show_watch_provider"
        ),
        schema="catalog",
    )
    op.create_index(
        "ix_show_watch_provider_provider_id",
        "show_watch_provider",
        ["provider_id"],
        unique=False,
        schema="catalog",
    )
    op.create_table(
        "translation",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("language_code", sa.Text(), nullable=False),
        sa.Column("country_code", sa.Text(), nullable=False),
        sa.Column("language_name", sa.Text(), nullable=True),
        sa.Column("language_english_name", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("tagline", sa.Text(), nullable=True),
        sa.Column("homepage", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "show_id", "language_code", "country_code", name="uq_translation_show_locale"
        ),
        schema="catalog",
    )
    op.create_table(
        "video",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        sa.Column("tmdb_id", sa.Text(), nullable=True),
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("key", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("site", sa.Text(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("type", sa.Text(), nullable=True),
        sa.Column("official", sa.Boolean(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("language_code", sa.Text(), nullable=True),
        sa.Column("country_code", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tmdb_id", name="uq_video_tmdb_id"),
        schema="catalog",
    )
    op.create_index("ix_video_show_id", "video", ["show_id"], unique=False, schema="catalog")
    op.create_table(
        "episode",
        sa.Column(
            "id", sa.BigInteger(), sa.Identity(always=False, start=10000000), nullable=False
        ),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("season_id", sa.BigInteger(), nullable=True),
        sa.Column("season_number", sa.Integer(), nullable=False),
        sa.Column("episode_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("air_date", sa.Date(), nullable=True),
        sa.Column("runtime", sa.Integer(), nullable=True),
        sa.Column("still_path", sa.Text(), nullable=True),
        sa.Column("production_code", sa.Text(), nullable=True),
        sa.Column("episode_type", sa.Text(), nullable=True),
        sa.Column("vote_average", sa.Numeric(precision=5, scale=3), nullable=True),
        sa.Column("vote_count", sa.Integer(), nullable=True),
        sa.Column(
            "screened_theatrically",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["season_id"], ["catalog.season.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["show_id"], ["catalog.show.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tmdb_id", name="uq_episode_tmdb_id"),
        schema="catalog",
    )
    op.create_index("ix_episode_season_id", "episode", ["season_id"], unique=False, schema="catalog")
    op.create_index(
        "ix_episode_show_id_season_number",
        "episode",
        ["show_id", "season_number"],
        unique=False,
        schema="catalog",
    )
    op.create_table(
        "season_network",
        sa.Column("season_id", sa.BigInteger(), nullable=False),
        sa.Column("network_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["network_id"], ["catalog.network.id"]),
        sa.ForeignKeyConstraint(["season_id"], ["catalog.season.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("season_id", "network_id", name="pk_season_network"),
        schema="catalog",
    )
    op.create_index(
        "ix_season_network_network_id",
        "season_network",
        ["network_id"],
        unique=False,
        schema="catalog",
    )

    # The back-edge of the show <-> episode cycle, now that both tables exist.
    op.create_foreign_key(
        "fk_show_last_episode_to_air",
        "show",
        "episode",
        ["last_episode_to_air_id"],
        ["id"],
        source_schema="catalog",
        referent_schema="catalog",
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_show_next_episode_to_air",
        "show",
        "episode",
        ["next_episode_to_air_id"],
        ["id"],
        source_schema="catalog",
        referent_schema="catalog",
        ondelete="SET NULL",
    )

    # Search indexes, ported from `tvmaze`. The raw-name pair backs ILIKE-style
    # matching; the folded pair backs the accent- and punctuation-insensitive
    # search `browse_queries._fold` builds, which is what lets "shogun" reach
    # "Shōgun". `pg_trgm` and `immutable_unaccent` already exist (2c05c4a1d7cb,
    # c2e451aa1ec6).
    op.execute("CREATE INDEX ix_show_name_trgm ON catalog.show USING gin (name gin_trgm_ops)")
    op.execute(
        f"CREATE INDEX ix_show_name_folded_trgm ON catalog.show "
        f"USING gin ({_FOLDED.format(col='name')} gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_show_aka_title_trgm ON catalog.show_aka "
        "USING gin (title gin_trgm_ops)"
    )
    # No `tvmaze` counterpart, and that is a gap rather than a precedent:
    # AKA search folds the stored title exactly as it folds the show name, so
    # without this the AKA half of every search falls back to a table scan.
    op.execute(
        f"CREATE INDEX ix_show_aka_title_folded_trgm ON catalog.show_aka "
        f"USING gin ({_FOLDED.format(col='title')} gin_trgm_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS catalog.ix_show_aka_title_folded_trgm")
    op.execute("DROP INDEX IF EXISTS catalog.ix_show_aka_title_trgm")
    op.execute("DROP INDEX IF EXISTS catalog.ix_show_name_folded_trgm")
    op.execute("DROP INDEX IF EXISTS catalog.ix_show_name_trgm")

    # Before `episode` can be dropped, the cycle has to be broken.
    op.drop_constraint("fk_show_next_episode_to_air", "show", schema="catalog", type_="foreignkey")
    op.drop_constraint("fk_show_last_episode_to_air", "show", schema="catalog", type_="foreignkey")

    op.drop_index("ix_season_network_network_id", table_name="season_network", schema="catalog")
    op.drop_table("season_network", schema="catalog")
    op.drop_index("ix_episode_show_id_season_number", table_name="episode", schema="catalog")
    op.drop_index("ix_episode_season_id", table_name="episode", schema="catalog")
    op.drop_table("episode", schema="catalog")
    op.drop_index("ix_video_show_id", table_name="video", schema="catalog")
    op.drop_table("video", schema="catalog")
    op.drop_table("translation", schema="catalog")
    op.drop_index(
        "ix_show_watch_provider_provider_id", table_name="show_watch_provider", schema="catalog"
    )
    op.drop_table("show_watch_provider", schema="catalog")
    op.drop_table("show_spoken_language", schema="catalog")
    op.drop_table("show_production_country", schema="catalog")
    op.drop_index(
        "ix_show_production_company_company_id",
        table_name="show_production_company",
        schema="catalog",
    )
    op.drop_table("show_production_company", schema="catalog")
    op.drop_table("show_origin_country", schema="catalog")
    op.drop_index("ix_show_network_network_id", table_name="show_network", schema="catalog")
    op.drop_table("show_network", schema="catalog")
    op.drop_table("show_language", schema="catalog")
    op.drop_index("ix_show_keyword_keyword_id", table_name="show_keyword", schema="catalog")
    op.drop_table("show_keyword", schema="catalog")
    op.drop_index("ix_show_genre_genre_id", table_name="show_genre", schema="catalog")
    op.drop_table("show_genre", schema="catalog")
    op.drop_index("ix_season_show_id_number", table_name="season", schema="catalog")
    op.drop_table("season", schema="catalog")
    op.drop_table("image", schema="catalog")
    op.drop_index("ix_episode_group_show_id", table_name="episode_group", schema="catalog")
    op.drop_table("episode_group", schema="catalog")
    op.drop_table("content_rating", schema="catalog")
    op.drop_table("show_creator", schema="catalog")
    op.drop_index("ix_show_aka_show_id", table_name="show_aka", schema="catalog")
    op.drop_table("show_aka", schema="catalog")
    op.drop_index("ix_show_tvdb_id", table_name="show", schema="catalog")
    op.drop_index("ix_show_imdb_id", table_name="show", schema="catalog")
    op.drop_table("show", schema="catalog")
    op.drop_table("watch_provider", schema="catalog")
    op.drop_table("production_company", schema="catalog")
    op.drop_table("network", schema="catalog")
    op.drop_table("language", schema="catalog")
    op.drop_table("keyword", schema="catalog")
    op.drop_table("genre", schema="catalog")
    op.drop_table("country", schema="catalog")
