"""add catalog.rate_budget

The keyed request budget (NEU-1027). `tvmaze.rate_budget` holds exactly one
upstream's ceiling in a single check-constrained row; this one holds a row per
source, so TMDB gets its own without disturbing TV Maze's — both run side by
side until cutover.

No seed row. Capacity is whatever the caller's settings say, and the limiter
seeds its own row at that capacity on first use, so seeding a number here would
only be a second place for it to be wrong.

Hand-written rather than autogenerated: autogenerate on this repo proposes
dropping seven production indexes it cannot see in the metadata, including the
GIN trigram index behind AKA search.

Revision ID: b1e4c7d90a52
Revises: 34a25a5fe59e
Create Date: 2026-08-09

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b1e4c7d90a52"
down_revision: str | Sequence[str] | None = "34a25a5fe59e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "rate_budget",
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("tokens", sa.Double(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("source"),
        schema="catalog",
    )


def downgrade() -> None:
    op.drop_table("rate_budget", schema="catalog")
