"""add app.watch_archive

The source-independent snapshot of every watch and rating record (NEU-1029) —
the backstop that decouples the TMDB migration's no-loss guarantee from the
migration itself. See `WatchArchive` in `tvbf/app/models.py` for why each
constraint is shaped the way it is.

Hand-written rather than autogenerated: autogenerate on this repo proposes
dropping seven production indexes it cannot see in the metadata, including the
GIN trigram index behind AKA search.

Revision ID: c9f2b7a41d38
Revises: b1e4c7d90a52
Create Date: 2026-08-09

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c9f2b7a41d38"
down_revision: str | Sequence[str] | None = "b1e4c7d90a52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


watch_archive_record_type = postgresql.ENUM(
    "show_watch",
    "episode_watch",
    "show_rating",
    "episode_rating",
    name="watch_archive_record_type",
    schema="app",
)


def upgrade() -> None:
    watch_archive_record_type.create(op.get_bind(), checkfirst=False)

    op.create_table(
        "watch_archive",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "record_type",
            postgresql.ENUM(
                name="watch_archive_record_type",
                schema="app",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_email", sa.Text(), nullable=False),
        sa.Column("user_display_name", sa.Text(), nullable=False),
        sa.Column("show_name", sa.Text(), nullable=False),
        sa.Column("show_premiered_year", sa.Integer(), nullable=True),
        sa.Column("season_number", sa.Integer(), nullable=True),
        sa.Column("episode_number", sa.Integer(), nullable=True),
        sa.Column("episode_title", sa.Text(), nullable=True),
        sa.Column("episode_airdate", sa.Date(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stars", sa.Numeric(2, 1), nullable=True),
        sa.Column("source_show_id", sa.BigInteger(), nullable=False),
        sa.Column("source_episode_id", sa.BigInteger(), nullable=True),
        sa.Column("show_imdb_id", sa.Text(), nullable=True),
        sa.Column("show_tvdb_id", sa.Integer(), nullable=True),
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "(record_type IN ('episode_watch', 'episode_rating')) "
            "= (source_episode_id IS NOT NULL)",
            name="ck_watch_archive_episode_grain",
        ),
        sa.CheckConstraint(
            "record_type IN ('show_watch', 'show_rating') "
            "OR (season_number IS NOT NULL "
            "AND (episode_number IS NOT NULL OR episode_title IS NOT NULL))",
            name="ck_watch_archive_episode_identity",
        ),
        sa.CheckConstraint(
            "(record_type IN ('show_rating', 'episode_rating')) = (stars IS NOT NULL)",
            name="ck_watch_archive_rating_stars",
        ),
        # NULLS NOT DISTINCT: show-grain rows carry a NULL `source_episode_id`,
        # and under the default every re-run would duplicate them instead of
        # conflicting.
        sa.UniqueConstraint(
            "record_type",
            "user_id",
            "source_show_id",
            "source_episode_id",
            name="uq_watch_archive_source_row",
            postgresql_nulls_not_distinct=True,
        ),
        schema="app",
    )

    op.create_index(
        "ix_watch_archive_user_id",
        "watch_archive",
        ["user_id"],
        schema="app",
    )

    # Append-only, enforced rather than asserted. The archive is the migration's
    # last line of defence, so "never updated, never pruned" belongs in the DDL
    # where a stray UPDATE, a future service, or a hand-run psql session all meet
    # it — not only in the writer's `ON CONFLICT DO NOTHING`.
    # Spelled out rather than imported from `tvbf.app.models`, which attaches the
    # same two statements to the table's create event for the test suite's
    # `create_all`. A migration is a snapshot of history and must not change
    # meaning when the model later does — the duplication is the point. Any edit
    # here needs the matching edit there, and vice versa.
    op.execute("""
        CREATE OR REPLACE FUNCTION app.watch_archive_no_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION
                'app.watch_archive is append-only: % is not permitted', TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$
    """)
    op.execute("""
        CREATE OR REPLACE TRIGGER watch_archive_no_mutation
        BEFORE UPDATE OR DELETE ON app.watch_archive
        FOR EACH ROW EXECUTE FUNCTION app.watch_archive_no_mutation()
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER watch_archive_no_mutation ON app.watch_archive")
    op.execute("DROP FUNCTION app.watch_archive_no_mutation()")
    op.drop_index("ix_watch_archive_user_id", table_name="watch_archive", schema="app")
    op.drop_table("watch_archive", schema="app")
    watch_archive_record_type.drop(op.get_bind(), checkfirst=False)
