"""Index catalog.show.first_air_date for the most-anticipated query

The most-anticipated surface (NEU-1058) is a live query rather than a snapshot:
a `first_air_date` range from today out to the configured window, ordered by
popularity. Measured on the production mirror it runs 45 ms unindexed — a
parallel sequential scan of 229k shows plus a top-N heapsort over the 408 rows
that survive the filter — which is already acceptable behind the browse routes'
`Cache-Control: public, max-age=300`. This makes it a range scan.

**The partial predicate is `deleted_upstream_at IS NULL` and nothing else.**
`current_date` is *stable*, not *immutable*, so it cannot appear in an index
predicate; Postgres rejects the statement outright. Index the column, not the
comparison — the date range is a query-time condition the btree already serves.

Hand-written rather than autogenerated, on `f85a608ef19e`'s precedent: the
trigram and FK indexes are declared in migrations rather than in `models.py`, so
autogenerate proposes dropping them alongside any create it is asked for.

Revision ID: d4b2e9c60a17
Revises: c9a1f0b7d213
Create Date: 2026-08-16 16:20:00.000000+00:00

"""

import sqlalchemy as sa
from alembic import op

revision = "d4b2e9c60a17"
down_revision = "c9a1f0b7d213"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_index(
        "ix_show_first_air_date_live",
        "show",
        ["first_air_date"],
        unique=False,
        schema="catalog",
        postgresql_where=sa.text("deleted_upstream_at IS NULL"),
    )


def downgrade() -> None:
    op.drop_index("ix_show_first_air_date_live", table_name="show", schema="catalog")
