"""Index the show->episode air FKs so cascaded episode deletes do not seq scan

`catalog.show.last_episode_to_air_id` and `next_episode_to_air_id` are
`ON DELETE SET NULL` foreign keys into `catalog.episode`, and neither had an
index. Postgres has to find the referencing rows every time an episode is
deleted, so unindexed that is a sequential scan of all 255,010 shows **per
deleted episode**. Measured against production on 2026-08-11: deleting a single
show with 10-40 episodes ran past 60 seconds and was still going, which is what
stopped `task prune:shows` (NEU-1066) from completing even one batch.

Every other foreign key into the catalog spine already has a leading index, by
accident of sitting on a lookup path. These two have no read path — nothing
queries a show *by* its last-aired episode — so nothing gave them one, and the
cost stayed invisible until a pass deleted episodes in bulk.

**Hand-written, not autogenerated.** `alembic revision --autogenerate` proposed
these two creates alongside eleven `drop_index` calls for the trigram and FK
indexes that are declared in migrations rather than in `models.py` — including
every index browse search depends on. Only the two creates are kept.

Revision ID: f85a608ef19e
Revises: c1f7a5d20b93
Create Date: 2026-08-11 23:35:09.332058+00:00

"""

from alembic import op

revision = "f85a608ef19e"
down_revision = "c1f7a5d20b93"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_index(
        "ix_show_last_episode_to_air_id",
        "show",
        ["last_episode_to_air_id"],
        unique=False,
        schema="catalog",
    )
    op.create_index(
        "ix_show_next_episode_to_air_id",
        "show",
        ["next_episode_to_air_id"],
        unique=False,
        schema="catalog",
    )


def downgrade() -> None:
    op.drop_index("ix_show_next_episode_to_air_id", table_name="show", schema="catalog")
    op.drop_index("ix_show_last_episode_to_air_id", table_name="show", schema="catalog")
