"""The `catalog` table definitions (NEU-1032).

These are the properties that make the migration safe to run and the schema safe
to build on — not a tour of the columns. Each one fails loudly if a convention
from `docs/specs/NEU-1031-tmdb-coverage-audit.md` or ADR-0008 is quietly undone.
"""

import pytest
from sqlalchemy import select
from sqlalchemy.exc import DBAPIError, IntegrityError

from tvbf.catalog import models as m


async def _show(session, **kwargs) -> m.Show:
    show = m.Show(name=kwargs.pop("name", "A Show"), **kwargs)
    session.add(show)
    await session.flush()
    return show


class TestSurrogateIdentities:
    """ADR-0008's surrogate keys, and the sequence starts that let the migration
    preserve TV Maze's ids underneath them."""

    async def test_explicit_id_below_the_start_never_collides_with_a_generated_one(self, session):
        """The acceptance criterion, stated as the failure it prevents.

        The migration inserts explicit ids to keep TV Maze's — prod's highest
        show id is 93,469 — and every generated id has to land clear of them.
        """
        preserved = await _show(session, id=93_469, tmdb_id=1, name="Migrated")
        generated = await _show(session, tmdb_id=2, name="Born here")

        assert preserved.id == 93_469
        assert generated.id >= 1_000_000

    async def test_each_spine_table_starts_above_tv_mazes_high_water_mark(self, session):
        """Prod's maxima are show 93,469 / season 204,038 / episode 3,694,622."""
        show = await _show(session, tmdb_id=10)
        season = m.Season(show_id=show.id, tmdb_id=20, season_number=1)
        session.add(season)
        await session.flush()
        episode = m.Episode(
            show_id=show.id, season_id=season.id, tmdb_id=30, season_number=1, episode_number=1
        )
        session.add(episode)
        await session.flush()

        assert show.id >= 1_000_000
        assert season.id >= 1_000_000
        assert episode.id >= 10_000_000

    async def test_an_explicit_id_does_not_advance_the_sequence(self, session):
        """`GENERATED BY DEFAULT` leaves the sequence alone when an id is supplied.

        Which is exactly why the starts have to clear the migrated range on their
        own: inserting 93,469 rows explicitly does not push the counter past them.
        """
        await _show(session, id=500_000, tmdb_id=1)
        generated = await _show(session, tmdb_id=2)

        assert generated.id == 1_000_000


class TestLocallyAuthoredRows:
    """`tmdb_id IS NULL` is a permanent, sanctioned state (ADR-0008), so the
    unique key has to tolerate any number of them."""

    async def test_many_rows_may_have_no_upstream_id(self, session):
        first = await _show(session, name="Not on TMDB")
        second = await _show(session, name="Also not on TMDB")

        assert first.tmdb_id is None and second.tmdb_id is None
        assert first.id != second.id

    async def test_two_rows_may_not_share_an_upstream_id(self, session):
        await _show(session, tmdb_id=1399)
        session.add(m.Show(name="Impostor", tmdb_id=1399))

        with pytest.raises(IntegrityError):
            await session.flush()


class TestIsEnded:
    """The one piece of status that carries behavior (audit D1).

    It is a generated column rather than something ingest writes, so it cannot
    drift from `status` — and `Canceled` counting as ended is the whole point:
    a straight port of `status == "Ended"` reclassifies every canceled show as
    still-running.
    """

    @pytest.mark.parametrize(
        ("status", "expected"),
        [
            ("Ended", True),
            ("Canceled", True),
            ("Returning Series", False),
            ("In Production", False),
            ("Planned", False),
            (None, False),
        ],
    )
    async def test_derived_from_status(self, session, status, expected):
        show = await _show(session, status=status)
        await session.refresh(show)

        assert show.is_ended is expected

    async def test_follows_a_status_change_without_being_written(self, session):
        show = await _show(session, status="Returning Series")
        await session.refresh(show)
        assert show.is_ended is False

        show.status = "Canceled"
        await session.flush()
        await session.refresh(show)

        assert show.is_ended is True

    async def test_cannot_be_written_directly(self, session):
        session.add(m.Show(name="Liar", status="Returning Series", is_ended=True))

        with pytest.raises(DBAPIError):
            await session.flush()


class TestSeasonNumbering:
    """No `UNIQUE (show_id, season_number)` — deliberately (see the model).

    TMDB was measured not to reuse a season number, but 754 resolved shows is a
    rounding error against its ~228k series, upserts conflict-target `tmdb_id`
    instead, and the downside is an integrity error that kills a multi-hour pass.
    """

    async def test_a_show_may_carry_two_seasons_with_the_same_number(self, session):
        show = await _show(session, tmdb_id=1)
        session.add_all(
            [
                m.Season(show_id=show.id, tmdb_id=10, season_number=1),
                m.Season(show_id=show.id, tmdb_id=11, season_number=1),
            ]
        )
        await session.flush()

        rows = (
            await session.execute(select(m.Season).where(m.Season.show_id == show.id))
        ).scalars()
        assert len({r.id for r in rows}) == 2


class TestSpecialsAreSeasonZero:
    """Audit D2: a special is season 0 with a real episode number, not the null
    number TV Maze used."""

    async def test_season_zero_is_an_ordinary_season(self, session):
        show = await _show(session, tmdb_id=1)
        season = m.Season(show_id=show.id, tmdb_id=10, season_number=0, name="Specials")
        session.add(season)
        await session.flush()
        session.add(
            m.Episode(
                show_id=show.id,
                season_id=season.id,
                tmdb_id=100,
                season_number=0,
                episode_number=1,
            )
        )
        await session.flush()

        stored = (
            await session.execute(select(m.Episode).where(m.Episode.show_id == show.id))
        ).scalar_one()
        assert (stored.season_number, stored.episode_number) == (0, 1)

    async def test_an_episode_number_is_required(self, session):
        show = await _show(session, tmdb_id=1)
        session.add(m.Episode(show_id=show.id, tmdb_id=100, season_number=0))

        with pytest.raises((IntegrityError, DBAPIError)):
            await session.flush()


class TestDeleteBehaviour:
    """Cascades, and the one place a cascade would destroy user history."""

    async def test_deleting_a_season_leaves_its_episodes(self, session):
        """`SET NULL`, not `CASCADE`. A season pruned because the payload stopped
        naming it (ADR-0004) must not take watch history with it."""
        show = await _show(session, tmdb_id=1)
        season = m.Season(show_id=show.id, tmdb_id=10, season_number=1)
        session.add(season)
        await session.flush()
        episode = m.Episode(
            show_id=show.id, season_id=season.id, tmdb_id=100, season_number=1, episode_number=1
        )
        session.add(episode)
        await session.flush()

        await session.delete(season)
        await session.flush()
        await session.refresh(episode)

        assert episode.season_id is None
        assert episode.show_id == show.id

    async def test_deleting_a_show_takes_its_episodes(self, session):
        show = await _show(session, tmdb_id=1)
        session.add(m.Episode(show_id=show.id, tmdb_id=100, season_number=1, episode_number=1))
        await session.flush()

        await session.delete(show)
        await session.flush()

        remaining = (await session.execute(select(m.Episode))).scalars().all()
        assert remaining == []

    async def test_an_episode_pointer_survives_the_episode_going_away(self, session):
        """`show.next_episode_to_air_id` is a cache, so losing its target must
        blank the pointer rather than fail the delete."""
        show = await _show(session, tmdb_id=1)
        episode = m.Episode(show_id=show.id, tmdb_id=100, season_number=1, episode_number=1)
        session.add(episode)
        await session.flush()
        show.next_episode_to_air_id = episode.id
        await session.flush()

        await session.delete(episode)
        await session.flush()
        await session.refresh(show)

        assert show.next_episode_to_air_id is None


class TestConstrainedVocabularies:
    """Two CHECKs, and the reason there are only two.

    `offer_type` and `image.kind` enumerate keys of a response object we read —
    ours to name. `show.status` and `episode.episode_type` are TMDB's own free
    text, and a CHECK on either would abort an ingest over a value upstream
    invented, which is the `tvmaze.season` unique-key mistake in another costume.
    """

    async def test_an_unknown_offer_type_is_rejected(self, session):
        show = await _show(session, tmdb_id=1)
        # No `relationship()` anywhere in this schema, so the unit of work
        # cannot infer that `country` has to be inserted first.
        session.add(m.Country(iso_3166_1="US"))
        provider = m.WatchProvider(tmdb_id=8, name="Netflix")
        session.add(provider)
        await session.flush()
        session.add(
            m.ShowWatchProvider(
                show_id=show.id, country_code="US", offer_type="barter", provider_id=provider.id
            )
        )

        with pytest.raises(IntegrityError):
            await session.flush()

    async def test_an_unknown_image_kind_is_rejected(self, session):
        show = await _show(session, tmdb_id=1)
        session.add(m.Image(show_id=show.id, kind="thumbnail", file_path="/x.jpg"))

        with pytest.raises(IntegrityError):
            await session.flush()

    @pytest.mark.parametrize("status", ["Returning Series", "Canceled", "Some New Thing"])
    async def test_any_status_string_is_accepted(self, session, status):
        show = await _show(session, status=status)

        assert show.status == status

    async def test_any_episode_type_is_accepted(self, session):
        show = await _show(session, tmdb_id=1)
        session.add(
            m.Episode(
                show_id=show.id,
                tmdb_id=100,
                season_number=1,
                episode_number=1,
                episode_type="something_new",
            )
        )
        await session.flush()

        stored = (await session.execute(select(m.Episode))).scalar_one()
        assert stored.episode_type == "something_new"


class TestThreeLanguageConcepts:
    """Audit D3 — `original_language`, `languages[]` and `spoken_languages[]` are
    three different things, and collapsing them would be lossy."""

    async def test_they_are_stored_separately(self, session):
        session.add_all(
            [
                m.Language(iso_639_1="en", english_name="English", name="English"),
                m.Language(iso_639_1="de", english_name="German", name="Deutsch"),
                m.Language(iso_639_1="es", english_name="Spanish", name="Español"),
            ]
        )
        show = await _show(session, tmdb_id=1396, name="Breaking Bad", original_language="en")
        session.add_all(
            [m.ShowLanguage(show_id=show.id, language_code=c) for c in ("en", "de", "es")]
        )
        session.add_all(
            [m.ShowSpokenLanguage(show_id=show.id, language_code=c) for c in ("en", "de", "es")]
        )
        await session.flush()

        available = (
            await session.execute(
                select(m.ShowLanguage.language_code).where(m.ShowLanguage.show_id == show.id)
            )
        ).scalars()
        assert show.original_language == "en"
        assert sorted(available) == ["de", "en", "es"]


class TestShowCreators:
    """`created_by` is a show-creator credit, which TMDB models separately from
    crew — and so, per the audit, do we. It carries no FK to `catalog.person`,
    which does not exist yet (NEU-1038)."""

    async def test_a_show_may_have_several_creators(self, session):
        show = await _show(session, tmdb_id=1396, name="Breaking Bad")
        session.add_all(
            [
                m.ShowCreator(
                    show_id=show.id, tmdb_person_id=66633, credit_id="52542282760ee3", name="A"
                ),
                m.ShowCreator(
                    show_id=show.id, tmdb_person_id=1223786, credit_id="52542282760ee4", name="B"
                ),
            ]
        )
        await session.flush()

        creators = (
            await session.execute(
                select(m.ShowCreator.name).where(m.ShowCreator.show_id == show.id)
            )
        ).scalars()
        assert sorted(creators) == ["A", "B"]

    async def test_the_same_credit_cannot_be_recorded_twice(self, session):
        show = await _show(session, tmdb_id=1396)
        session.add(m.ShowCreator(show_id=show.id, credit_id="dup", name="A"))
        await session.flush()
        session.add(m.ShowCreator(show_id=show.id, credit_id="dup", name="A"))

        with pytest.raises(IntegrityError):
            await session.flush()

    async def test_creators_without_an_upstream_credit_id_do_not_conflict(self, session):
        """`NULLS DISTINCT` is the default and the right one here — two
        locally-authored creators have no upstream credit to collide on."""
        show = await _show(session, tmdb_id=1396)
        session.add_all(
            [
                m.ShowCreator(show_id=show.id, name="Local one"),
                m.ShowCreator(show_id=show.id, name="Local two"),
            ]
        )
        await session.flush()

        count = (
            await session.execute(select(m.ShowCreator).where(m.ShowCreator.show_id == show.id))
        ).scalars()
        assert len(list(count)) == 2


class TestArrayColumns:
    """Two lists that are stored as arrays because nothing joins on them."""

    async def test_episode_run_time_round_trips(self, session):
        show = await _show(session, tmdb_id=1, episode_run_time=[25, 50])
        await session.refresh(show)

        assert show.episode_run_time == [25, 50]

    async def test_content_rating_descriptors_round_trip(self, session):
        show = await _show(session, tmdb_id=1)
        session.add(m.Country(iso_3166_1="US"))
        await session.flush()
        rating = m.ContentRating(
            show_id=show.id, country_code="US", rating="TV-MA", descriptors=["violence", "language"]
        )
        session.add(rating)
        await session.flush()
        await session.refresh(rating)

        assert rating.descriptors == ["violence", "language"]
