"""The source-neutral catalog mirror (ADR-0007), modeled on TMDB's full response surface.

Scope is deliberately **TMDB inward, not TV Maze outward**: every field
NEU-1031's coverage audit classified *modeled* has a column here, whether or not
`tvmaze/models.py` had an ancestor for it. `append_to_response` rides content
ratings, keywords, watch providers, translations and the rest on a request we
already make, so the marginal cost of a field is a column rather than a
multi-hour pass — which is how the TV Maze mirror accumulated four backfills.
See `docs/specs/NEU-1031-tmdb-coverage-audit.md`; every column below traces to a
row in it.

Three conventions hold across the whole schema.

**Surrogate primary key, upstream id alongside.** Every entity carries a
generated `id` and a unique, nullable `tmdb_id` (ADR-0008). `app` references the
surrogate, upserts conflict-target `tmdb_id`, and `tmdb_id IS NULL` means the row
is **locally-authored** — the sanctioned way to hold a show a user tracks that
TMDB does not list. Ingest never deletes or overwrites one.

**Identities are `GENERATED BY DEFAULT`, never `ALWAYS`, and start above TV
Maze's high-water mark.** The migration inserts explicit ids to preserve TV
Maze's, which `ALWAYS` would reject; the sequence starts keep a generated id from
ever landing on one of them. See `_SHOW_ID_START` and friends.

**No `relationship()` declarations.** Nothing navigates via the ORM — it all
reads through `select()` and FK columns. A test fixture inserting a parent and a
child in one `commit()` therefore needs an explicit `await session.flush()`
between them, because the unit of work cannot infer insert order without one.

Credits — person, per-show character, crew role, cast, crew, guest cast — land at
the bottom of this module (NEU-1038). The `created_by` show-creator credit is
*not* among them: TMDB models it separately from crew and so does `ShowCreator`.
"""

from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import (
    ARRAY,
    BigInteger,
    Boolean,
    CheckConstraint,
    Computed,
    Date,
    DateTime,
    Double,
    ForeignKey,
    Identity,
    Index,
    Integer,
    Numeric,
    PrimaryKeyConstraint,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.orm import Mapped, mapped_column

from tvbf.db import Base

SCHEMA = "catalog"

# Where the generated identities start.
#
# The migration preserves TV Maze's ids as `catalog.*.id` so `app`'s existing
# rows keep pointing at the right catalog row without being rewritten. Prod's
# maxima are show 93,469 / season 204,038 / episode 3,694,622; starting the
# sequences well clear of those means a generated id can never collide with a
# preserved one, and the gap leaves room for the mirror to have grown between
# now and cutover.
_SHOW_ID_START = 1_000_000
_SEASON_ID_START = 1_000_000
_EPISODE_ID_START = 10_000_000


def _surrogate(start: int = 1) -> Identity:
    """`GENERATED BY DEFAULT AS IDENTITY`, optionally starting past the migrated ids.

    `always=False` is the load-bearing half: the migration supplies explicit ids
    and `GENERATED ALWAYS` would refuse them outright.
    """
    return Identity(always=False, start=start)


class Country(Base):
    """ISO 3166-1 country codes, with TMDB's English name where it gives one.

    Natural key rather than a surrogate, unlike every entity around it: this is a
    static external vocabulary, not a TMDB record — there is no `tmdb_id` to
    conflict on and nothing locally-authored to express. `name` is nullable
    because `origin_country[]` and `content_ratings[]` supply bare codes; only
    `production_countries[]` carries a name.
    """

    __tablename__ = "country"
    __table_args__ = ({"schema": SCHEMA},)

    iso_3166_1: Mapped[str] = mapped_column(Text, primary_key=True)
    name: Mapped[str | None] = mapped_column(Text)


class Language(Base):
    """ISO 639-1 language codes. Natural key, for the same reason as `Country`.

    Populated from `spoken_languages[]`, which is the only place TMDB names a
    language; `languages[]` and `original_language` are bare codes.
    """

    __tablename__ = "language"
    __table_args__ = ({"schema": SCHEMA},)

    iso_639_1: Mapped[str] = mapped_column(Text, primary_key=True)
    english_name: Mapped[str | None] = mapped_column(Text)
    name: Mapped[str | None] = mapped_column(Text)


class Genre(Base):
    __tablename__ = "genre"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_genre_tmdb_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    tmdb_id: Mapped[int | None] = mapped_column(Integer)
    name: Mapped[str] = mapped_column(Text, nullable=False)


class Network(Base):
    """A broadcaster. Absorbs both `tvmaze.network` and `tvmaze.web_channel`.

    TMDB draws no distinction between the two (audit §6), so the browse filter
    reshapes from two lists to one.
    """

    __tablename__ = "network"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_network_tmdb_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    tmdb_id: Mapped[int | None] = mapped_column(Integer)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    logo_path: Mapped[str | None] = mapped_column(Text)
    origin_country: Mapped[str | None] = mapped_column(Text)


class ProductionCompany(Base):
    __tablename__ = "production_company"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_production_company_tmdb_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    tmdb_id: Mapped[int | None] = mapped_column(Integer)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    logo_path: Mapped[str | None] = mapped_column(Text)
    origin_country: Mapped[str | None] = mapped_column(Text)


class Keyword(Base):
    """A discovery tag. Free on the show request; the basis of Discovery and
    Personalized Recommendations, and a multi-hour backfill if skipped."""

    __tablename__ = "keyword"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_keyword_tmdb_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    tmdb_id: Mapped[int | None] = mapped_column(Integer)
    name: Mapped[str] = mapped_column(Text, nullable=False)


class WatchProvider(Base):
    """A streaming service, as named by TMDB's JustWatch partnership.

    **Displaying this data obliges us to attribute JustWatch per media item**, not
    in a sitewide footer, and in addition to TMDB — TMDB staff were asked directly
    and said so, and non-compliance is explicit grounds for revoking API access.
    The obligation attaches to display, not capture, so storing it here is free of
    it; the constraint binds whichever project first puts a provider on screen.
    Recorded on the table so it is inherited rather than rediscovered.
    """

    __tablename__ = "watch_provider"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_watch_provider_tmdb_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    tmdb_id: Mapped[int | None] = mapped_column(Integer)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    logo_path: Mapped[str | None] = mapped_column(Text)
    display_priority: Mapped[int | None] = mapped_column(Integer)


class Show(Base):
    __tablename__ = "show"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_show_tmdb_id"),
        # The migration's mapping tiers look shows up by these two and nothing
        # else (project spec: `/find` by tvdb_id, then imdb_id). Every other
        # external id is stored but never searched.
        Index("ix_show_tvdb_id", "tvdb_id"),
        Index("ix_show_imdb_id", "imdb_id"),
        CheckConstraint(
            "match_method IS NULL OR match_method IN ('tvdb_id', 'imdb_id', 'title_year')",
            name="ck_show_match_method",
        ),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(_SHOW_ID_START), primary_key=True)
    tmdb_id: Mapped[int | None] = mapped_column(Integer)
    # How the migration arrived at this row's `tmdb_id` (NEU-1043) — one of
    # `tvdb_id` / `imdb_id` / `title_year`, mirroring the three mapping tiers.
    #
    # **The point of it is that two of those tiers are exact and one is not.**
    # A bare `tmdb_id` makes a `/find` hit and a title guess indistinguishable
    # forever; this column is what lets tier 3 be read more sceptically, audited,
    # or retracted as a batch (`WHERE match_method = 'title_year'`) if the
    # go/no-go turns one up wrong.
    #
    # NULL means *this row was not mapped by the migration* — either nothing
    # matched it, or it is a row the TMDB ingest inserted directly, which knows
    # its `tmdb_id` without having had to match anything. It is not a fourth
    # tier, and `tmdb_id IS NULL AND match_method IS NULL` remains the
    # locally-authored row of ADR-0008.
    #
    # Unlike `status`, this vocabulary is ours, so a CHECK constraint is right:
    # a typo'd method is a bug in our own writer rather than an upstream value
    # we do not control.
    match_method: Mapped[str | None] = mapped_column(Text)

    name: Mapped[str] = mapped_column(Text, nullable=False)
    # The untranslated title, in the show's own language. Together with
    # `translation` this *is* the TVBF: Localization project.
    original_name: Mapped[str | None] = mapped_column(Text)
    overview: Mapped[str | None] = mapped_column(Text)
    tagline: Mapped[str | None] = mapped_column(Text)
    homepage: Mapped[str | None] = mapped_column(Text)
    type: Mapped[str | None] = mapped_column(Text)
    adult: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false"), default=False
    )

    # TMDB's string, stored verbatim — `Returning Series` / `Planned` /
    # `In Production` / `Ended` / `Canceled` (audit D1). All five were confirmed
    # against a 1,000-show sweep and no sixth value appeared
    # (`scripts/probe_tmdb_status_vocabulary.py`). Not translated to our old
    # four-value vocabulary: a translation layer would be maintained forever and
    # TMDB's is strictly more informative — `Canceled` is a distinction we cannot
    # currently express at all. No CHECK constraint for the same reason
    # `tvmaze.season` carries no unique key: a vocabulary we do not own is not
    # something to abort an ingest over.
    status: Mapped[str | None] = mapped_column(Text)
    # Generated, not written by ingest — the single piece of status that carries
    # behavior, and the one a straight port gets wrong. Every `status == "Ended"`
    # comparison routes through here instead; without it, canceled shows read as
    # still-running, breaking "finished" for exactly the shows most likely to be
    # finished. Computed in the database so it cannot drift from `status`.
    is_ended: Mapped[bool] = mapped_column(
        Boolean,
        Computed("coalesce(status IN ('Ended', 'Canceled'), false)", persisted=True),
        nullable=False,
    )
    # A genuinely separate boolean per the audit. Measured caveat: across the
    # same 1,000-show sweep it was perfectly determined by `status` (true for
    # Returning Series / In Production / Planned, false for Ended / Canceled), so
    # it carried no information `status` did not. Stored anyway — it rides the
    # same request, and the audit's claim was made about TMDB's model rather than
    # about one sample.
    in_production: Mapped[bool | None] = mapped_column(Boolean)

    first_air_date: Mapped[date | None] = mapped_column(Date)
    last_air_date: Mapped[date | None] = mapped_column(Date)

    # The browse `language` filter reads this (audit D3): it is the only one of
    # TMDB's three language concepts with exactly one value per show, which the
    # filter's exact-match semantics require. Note the values change shape — TV
    # Maze stored "English", TMDB stores "en". Not an FK to `language`: that
    # table is populated from `spoken_languages[]`, which need not contain a
    # show's original language, and an FK would make ingest order load-bearing
    # for no gain.
    original_language: Mapped[str | None] = mapped_column(Text)

    popularity: Mapped[float | None] = mapped_column(Double)
    vote_average: Mapped[Decimal | None] = mapped_column(Numeric(5, 3))
    # New at show grain: lets us weight a rating rather than trust a 10.0 from
    # three voters.
    vote_count: Mapped[int | None] = mapped_column(Integer)

    poster_path: Mapped[str | None] = mapped_column(Text)
    backdrop_path: Mapped[str | None] = mapped_column(Text)

    # Both **exclude season 0** — measured, and the same convention D2 adopts for
    # our own completion math.
    number_of_episodes: Mapped[int | None] = mapped_column(Integer)
    number_of_seasons: Mapped[int | None] = mapped_column(Integer)

    # TMDB's own series-level runtime array, stored verbatim, and usually empty:
    # 6 of 7 sampled shows returned `[]` (audit D4).
    episode_run_time: Mapped[list[int] | None] = mapped_column(ARRAY(Integer))
    # The scalar the SPA renders, derived at ingest as the **median of the show's
    # episode runtimes** — populated for 94.9% of episodes, against TMDB's
    # series-level field which is mostly absent. Median rather than mean so a
    # feature-length finale does not drag a 22-minute sitcom upward.
    #
    # **Ordering constraint, not a detail:** this cannot be finalised until every
    # season's episodes are in hand, including `get_tv_season` overflow, and must
    # be recomputed whenever the daily delta adds episodes.
    runtime: Mapped[int | None] = mapped_column(Integer)

    # Denormalised pointers, refreshed by the daily delta. Derivable from the
    # episode rows — but a derivable field still costs a full ~1.5-hour re-ingest
    # to add later, while a nullable FK costs nothing now, and TMDB's answer is
    # authoritative where ours is inference. Treat them as a cache: read a live
    # query where one is available.
    #
    # `use_alter` because show and episode reference each other. Postgres is
    # happy with the cycle; SQLAlchemy's table sort is not, and would refuse to
    # emit `create_all` without it.
    last_episode_to_air_id: Mapped[int | None] = mapped_column(
        ForeignKey(
            f"{SCHEMA}.episode.id",
            ondelete="SET NULL",
            use_alter=True,
            name="fk_show_last_episode_to_air",
        )
    )
    next_episode_to_air_id: Mapped[int | None] = mapped_column(
        ForeignKey(
            f"{SCHEMA}.episode.id",
            ondelete="SET NULL",
            use_alter=True,
            name="fk_show_next_episode_to_air",
        )
    )

    # `external_ids`, flattened onto the row rather than given a 1:1 table — the
    # shape `tvmaze.show.externals_*` already had, and the mapping tiers want
    # `tvdb_id` and `imdb_id` without a join. Measured set, 2026-08-09.
    imdb_id: Mapped[str | None] = mapped_column(Text)
    tvdb_id: Mapped[int | None] = mapped_column(Integer)
    tvrage_id: Mapped[int | None] = mapped_column(Integer)
    wikidata_id: Mapped[str | None] = mapped_column(Text)
    freebase_id: Mapped[str | None] = mapped_column(Text)
    freebase_mid: Mapped[str | None] = mapped_column(Text)
    facebook_id: Mapped[str | None] = mapped_column(Text)
    instagram_id: Mapped[str | None] = mapped_column(Text)
    twitter_id: Mapped[str | None] = mapped_column(Text)

    ingested_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    # When a **complete** TMDB payload was last mirrored onto this row — the
    # full catalog ingest's resumability watermark (NEU-1034), and the same
    # device `tvmaze.show.akas_synced_at` already is.
    #
    # It exists because "already ingested" and "row already present" are
    # different questions here, where under TV Maze they were the same one. The
    # migration copies ~89k shows into this table (NEU-1042) and maps a
    # `tmdb_id` onto most of them (NEU-1043), so those rows exist and are
    # correctly identified while still holding TV Maze data. An ingest resuming
    # on row-existence would skip exactly the shows users track.
    #
    # NULL therefore means *no full TMDB pass has covered this row yet* — true
    # of a copied row, and true of a locally-authored one forever.
    tmdb_synced_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # Set when the show stops appearing in the daily id export, i.e. TMDB has
    # deleted it. The row is never removed: `app.user_show_watch` and
    # `app.user_show_rating` cascade from here, so a delete would destroy user
    # data nothing upstream could restore (ADR-0005). Locally-authored rows are
    # exempt by definition — they were never in the feed.
    deleted_upstream_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class Season(Base):
    __tablename__ = "season"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_season_tmdb_id"),
        Index("ix_season_show_id_number", "show_id", "season_number"),
        {"schema": SCHEMA},
    )
    # **No UNIQUE (show_id, season_number)**, and that is a decision rather than a
    # port. TV Maze reuses a season number within one show on long-running
    # programs that catalogue by calendar year, and a unique key aborts ingestion
    # on exactly those. TMDB was checked for the same quirk and did not show it —
    # 0 of 754 resolved shows had a duplicate `season_number`
    # (`scripts/probe_tmdb_status_vocabulary.py`) — but 754 is a rounding error
    # against TMDB's ~228k TV series, the constraint buys nothing (upserts
    # conflict-target `tmdb_id`, not this pair), and the downside is an integrity
    # error that kills a multi-hour pass on a long-tail show. A plain index
    # carries the lookups instead.

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(_SEASON_ID_START), primary_key=True)
    tmdb_id: Mapped[int | None] = mapped_column(Integer)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    # 0 for specials (audit D2). Not nullable: TMDB always numbers a season.
    season_number: Mapped[int] = mapped_column(Integer, nullable=False)
    name: Mapped[str | None] = mapped_column(Text)
    overview: Mapped[str | None] = mapped_column(Text)
    poster_path: Mapped[str | None] = mapped_column(Text)
    air_date: Mapped[date | None] = mapped_column(Date)
    vote_average: Mapped[Decimal | None] = mapped_column(Numeric(5, 3))
    # From `seasons[]` on the series payload, not from the season payload itself.
    episode_count: Mapped[int | None] = mapped_column(Integer)


class Episode(Base):
    __tablename__ = "episode"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_episode_tmdb_id"),
        Index("ix_episode_show_id_season_number", "show_id", "season_number"),
        Index("ix_episode_season_id", "season_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(_EPISODE_ID_START), primary_key=True)
    tmdb_id: Mapped[int | None] = mapped_column(Integer)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    # SET NULL rather than CASCADE, matching `tvmaze.episode`: a season pruned
    # because the payload stopped naming it (ADR-0004) must not take user watch
    # history with it.
    season_id: Mapped[int | None] = mapped_column(
        ForeignKey(f"{SCHEMA}.season.id", ondelete="SET NULL")
    )
    # Denormalised from the season so aired-count and ordering queries need no
    # join — and so the season-0 predicate D2 requires is one column away.
    season_number: Mapped[int] = mapped_column(Integer, nullable=False)
    # Not nullable, unlike `tvmaze.episode.number`. A null number was TV Maze's
    # marker for a special; under TMDB a special is season 0 with a real episode
    # number (audit D2).
    episode_number: Mapped[int] = mapped_column(Integer, nullable=False)
    name: Mapped[str | None] = mapped_column(Text)
    overview: Mapped[str | None] = mapped_column(Text)
    # A date and nothing more. TMDB carries no time component, so
    # `tvmaze.episode.airtime` has no counterpart and retires with it (audit §6).
    air_date: Mapped[date | None] = mapped_column(Date)
    runtime: Mapped[int | None] = mapped_column(Integer)
    still_path: Mapped[str | None] = mapped_column(Text)
    production_code: Mapped[str | None] = mapped_column(Text)
    # `premiere` / `mid_season` / `finale` / `standard`, straight from upstream —
    # finale detection with no heuristic, which is what Push Notifications would
    # otherwise have to invent. No CHECK: the vocabulary is TMDB's, not ours.
    episode_type: Mapped[str | None] = mapped_column(Text)
    vote_average: Mapped[Decimal | None] = mapped_column(Numeric(5, 3))
    vote_count: Mapped[int | None] = mapped_column(Integer)
    # The whole of the `screened_theatrically` namespace, which returns nothing
    # but a list of episodes. A flag is the faithful shape; a table would be a
    # join to store one bit.
    screened_theatrically: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false"), default=False
    )


class ShowGenre(Base):
    __tablename__ = "show_genre"
    __table_args__ = (
        PrimaryKeyConstraint("show_id", "genre_id", name="pk_show_genre"),
        # The PK covers show->genre; browse filters the other way
        # (`genre_id IN (...) GROUP BY show_id`) and needs its own index.
        Index("ix_show_genre_genre_id", "genre_id"),
        {"schema": SCHEMA},
    )

    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    genre_id: Mapped[int] = mapped_column(ForeignKey(f"{SCHEMA}.genre.id"), nullable=False)


class ShowNetwork(Base):
    __tablename__ = "show_network"
    __table_args__ = (
        PrimaryKeyConstraint("show_id", "network_id", name="pk_show_network"),
        Index("ix_show_network_network_id", "network_id"),
        {"schema": SCHEMA},
    )
    # A join table where TV Maze had two scalar FKs. TMDB returns `networks[]`,
    # and a show genuinely can carry more than one.

    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    network_id: Mapped[int] = mapped_column(ForeignKey(f"{SCHEMA}.network.id"), nullable=False)


class SeasonNetwork(Base):
    """`networks` on the season payload — measured, and absent from the ticket's
    season inventory (audit §8). Mirrors the series field at season grain."""

    __tablename__ = "season_network"
    __table_args__ = (
        PrimaryKeyConstraint("season_id", "network_id", name="pk_season_network"),
        Index("ix_season_network_network_id", "network_id"),
        {"schema": SCHEMA},
    )

    season_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.season.id", ondelete="CASCADE"), nullable=False
    )
    network_id: Mapped[int] = mapped_column(ForeignKey(f"{SCHEMA}.network.id"), nullable=False)


class ShowProductionCompany(Base):
    __tablename__ = "show_production_company"
    __table_args__ = (
        PrimaryKeyConstraint("show_id", "company_id", name="pk_show_production_company"),
        Index("ix_show_production_company_company_id", "company_id"),
        {"schema": SCHEMA},
    )

    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    company_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.production_company.id"), nullable=False
    )


class ShowOriginCountry(Base):
    """`origin_country[]` — bare ISO 3166-1 codes."""

    __tablename__ = "show_origin_country"
    __table_args__ = (
        PrimaryKeyConstraint("show_id", "country_code", name="pk_show_origin_country"),
        {"schema": SCHEMA},
    )

    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    country_code: Mapped[str] = mapped_column(
        ForeignKey(f"{SCHEMA}.country.iso_3166_1"), nullable=False
    )


class ShowProductionCountry(Base):
    """`production_countries[]` — the same codes, plus a name `Country` holds."""

    __tablename__ = "show_production_country"
    __table_args__ = (
        PrimaryKeyConstraint("show_id", "country_code", name="pk_show_production_country"),
        {"schema": SCHEMA},
    )

    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    country_code: Mapped[str] = mapped_column(
        ForeignKey(f"{SCHEMA}.country.iso_3166_1"), nullable=False
    )


class ShowLanguage(Base):
    """`languages[]` — the languages a show is available in. Distinct from both
    `original_language` and `spoken_languages[]` (audit D3); Breaking Bad is
    `en` original, `["en","de","es"]` here."""

    __tablename__ = "show_language"
    __table_args__ = (
        PrimaryKeyConstraint("show_id", "language_code", name="pk_show_language"),
        {"schema": SCHEMA},
    )

    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    language_code: Mapped[str] = mapped_column(
        ForeignKey(f"{SCHEMA}.language.iso_639_1"), nullable=False
    )


class ShowSpokenLanguage(Base):
    """`spoken_languages[]` — the languages heard on screen."""

    __tablename__ = "show_spoken_language"
    __table_args__ = (
        PrimaryKeyConstraint("show_id", "language_code", name="pk_show_spoken_language"),
        {"schema": SCHEMA},
    )

    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    language_code: Mapped[str] = mapped_column(
        ForeignKey(f"{SCHEMA}.language.iso_639_1"), nullable=False
    )


class ShowKeyword(Base):
    __tablename__ = "show_keyword"
    __table_args__ = (
        PrimaryKeyConstraint("show_id", "keyword_id", name="pk_show_keyword"),
        Index("ix_show_keyword_keyword_id", "keyword_id"),
        {"schema": SCHEMA},
    )

    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    keyword_id: Mapped[int] = mapped_column(ForeignKey(f"{SCHEMA}.keyword.id"), nullable=False)


class ShowWatchProvider(Base):
    """Where a show can be watched, per country and per kind of offer.

    `link` points at TMDB's own watch page and is denormalised across the offer
    types of one country, because that is the grain the response gives it at and
    the grain a UI needs it at. TMDB deliberately provides no deep links and asks
    that you link there instead.

    See `WatchProvider` for the per-item JustWatch attribution this data carries
    the moment anything displays it.
    """

    __tablename__ = "show_watch_provider"
    __table_args__ = (
        PrimaryKeyConstraint(
            "show_id", "country_code", "offer_type", "provider_id", name="pk_show_watch_provider"
        ),
        Index("ix_show_watch_provider_provider_id", "provider_id"),
        # Our own vocabulary — the keys of the `watch/providers` response — not
        # upstream free text, so a CHECK is safe here where it is not on
        # `show.status`. A new offer kind is a migration, and should be.
        CheckConstraint(
            "offer_type IN ('flatrate', 'buy', 'rent', 'free', 'ads')",
            name="ck_show_watch_provider_offer_type",
        ),
        {"schema": SCHEMA},
    )

    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    country_code: Mapped[str] = mapped_column(
        ForeignKey(f"{SCHEMA}.country.iso_3166_1"), nullable=False
    )
    offer_type: Mapped[str] = mapped_column(Text, nullable=False)
    provider_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.watch_provider.id"), nullable=False
    )
    display_priority: Mapped[int | None] = mapped_column(Integer)
    link: Mapped[str | None] = mapped_column(Text)


class ContentRating(Base):
    """Per-country certification — `TV-MA`, `TV-14`, … . No TV Maze equivalent
    exists, which is why skipping it would be a backfill rather than a gap."""

    __tablename__ = "content_rating"
    __table_args__ = (
        UniqueConstraint("show_id", "country_code", name="uq_content_rating_show_country"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    country_code: Mapped[str] = mapped_column(
        ForeignKey(f"{SCHEMA}.country.iso_3166_1"), nullable=False
    )
    rating: Mapped[str | None] = mapped_column(Text)
    # An unordered bag of advisory labels ("violence", "language"). An array
    # rather than a table: nothing joins on them and they have no identity.
    descriptors: Mapped[list[str] | None] = mapped_column(ARRAY(Text))


class ShowAka(Base):
    """TMDB's `alternative_titles` — an **AKA**, the direct equivalent of
    `tvmaze.show_aka`.

    Named for the glossary term rather than the upstream namespace: `CONTEXT.md`
    fixes "AKA" as the word for this concept across both repos, and a table
    called `alternative_title` would give one concept two names.

    AKA-aware search survives intact — `browse_queries` matches a folded query
    token against the folded title, which the two trigram indexes in the
    migration back. They are expression indexes and cannot be declared here.
    """

    __tablename__ = "show_aka"
    __table_args__ = (
        Index("ix_show_aka_show_id", "show_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    title: Mapped[str] = mapped_column(Text, nullable=False)
    country_code: Mapped[str | None] = mapped_column(Text)
    # TMDB's own free-text note on the kind of title ("Working title", "DVD").
    type: Mapped[str | None] = mapped_column(Text)


class ShowCreator(Base):
    """`created_by[]` — a show-creator credit, which TMDB models separately from
    crew and so do we. A credit type TV Maze never had.

    Self-contained rather than pointing at `catalog.person`, which now exists
    below. Storing the payload as it arrives is the faithful shape: TMDB returns
    `created_by` denormalised, with the person's name, gender and profile path
    inline rather than as a reference, and a creator need not appear in
    `aggregate_credits` at all — so an FK would be a nullable one whose target
    row the credits ingest may never create. `tmdb_person_id` is what resolves to
    a `person_id` for a UI that wants to link the two; adding that column is an
    additive migration whenever something needs it.
    """

    __tablename__ = "show_creator"
    __table_args__ = (
        # `credit_id` is TMDB's stable id for this specific credit. Nullable, so
        # a locally-authored creator conflicts with nothing (NULLS DISTINCT).
        UniqueConstraint("show_id", "credit_id", name="uq_show_creator_show_credit"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    tmdb_person_id: Mapped[int | None] = mapped_column(Integer)
    credit_id: Mapped[str | None] = mapped_column(Text)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    original_name: Mapped[str | None] = mapped_column(Text)
    # TMDB's integer enum (0 unknown, 1 female, 2 male, 3 non-binary), passed
    # through rather than interpreted.
    gender: Mapped[int | None] = mapped_column(Integer)
    profile_path: Mapped[str | None] = mapped_column(Text)


class Translation(Base):
    """Localized `name` / `overview` / `tagline` / `homepage` per locale.

    The TVBF: Localization project *is* this table plus `show.original_name`. A
    locale is a language and a country together — TMDB returns `pt-BR` and
    `pt-PT` separately — so the unique key needs both.
    """

    __tablename__ = "translation"
    __table_args__ = (
        UniqueConstraint(
            "show_id", "language_code", "country_code", name="uq_translation_show_locale"
        ),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    language_code: Mapped[str] = mapped_column(Text, nullable=False)
    country_code: Mapped[str] = mapped_column(Text, nullable=False)
    # How the locale names itself, and its English name — TMDB's `name` and
    # `english_name`, kept distinct from the translated show `name` below.
    language_name: Mapped[str | None] = mapped_column(Text)
    language_english_name: Mapped[str | None] = mapped_column(Text)
    # The `data` object.
    name: Mapped[str | None] = mapped_column(Text)
    overview: Mapped[str | None] = mapped_column(Text)
    tagline: Mapped[str | None] = mapped_column(Text)
    homepage: Mapped[str | None] = mapped_column(Text)


class Image(Base):
    """`images` — backdrops, logos and posters, beyond the one poster and one
    backdrop the series row carries. Public Profiles & Sharing needs them."""

    __tablename__ = "image"
    __table_args__ = (
        UniqueConstraint("show_id", "kind", "file_path", name="uq_image_show_kind_path"),
        # Three keys of one response object, so this vocabulary is ours to
        # enumerate — unlike `show.status`.
        CheckConstraint("kind IN ('backdrop', 'logo', 'poster')", name="ck_image_kind"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    kind: Mapped[str] = mapped_column(Text, nullable=False)
    # TMDB gives images no id; the path is the identity.
    file_path: Mapped[str] = mapped_column(Text, nullable=False)
    aspect_ratio: Mapped[float | None] = mapped_column(Double)
    height: Mapped[int | None] = mapped_column(Integer)
    width: Mapped[int | None] = mapped_column(Integer)
    language_code: Mapped[str | None] = mapped_column(Text)
    vote_average: Mapped[Decimal | None] = mapped_column(Numeric(5, 3))
    vote_count: Mapped[int | None] = mapped_column(Integer)


class Video(Base):
    """`videos` — trailers, teasers, featurettes. Free on the same request."""

    __tablename__ = "video"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_video_tmdb_id"),
        Index("ix_video_show_id", "show_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    # Text, not Integer, unlike every other `tmdb_id` here: TMDB identifies a
    # video by a 24-character hex string. The column keeps the name because the
    # name is the convention — "the upstream key" — and only the type differs.
    tmdb_id: Mapped[str | None] = mapped_column(Text)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    # The id *within* the site — a YouTube watch id, say. Not TMDB's id.
    key: Mapped[str | None] = mapped_column(Text)
    name: Mapped[str | None] = mapped_column(Text)
    site: Mapped[str | None] = mapped_column(Text)
    size: Mapped[int | None] = mapped_column(Integer)
    type: Mapped[str | None] = mapped_column(Text)
    official: Mapped[bool | None] = mapped_column(Boolean)
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    language_code: Mapped[str | None] = mapped_column(Text)
    country_code: Mapped[str | None] = mapped_column(Text)


class EpisodeGroup(Base):
    """`episode_groups` — absolute and DVD orderings, for anime and long-running
    shows.

    Headers only, and deliberately so: the appended namespace returns one row per
    group with its counts, and the groups' actual episode assignments live behind
    a separate `/tv/episode_group/{id}` request that `append_to_response` cannot
    ride. Storing the headers is what the namespace offers; fetching the contents
    is a per-group request some later ordering feature can spend.
    """

    __tablename__ = "episode_group"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_episode_group_tmdb_id"),
        Index("ix_episode_group_show_id", "show_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    # A hex string, like `Video.tmdb_id`.
    tmdb_id: Mapped[str | None] = mapped_column(Text)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str | None] = mapped_column(Text)
    description: Mapped[str | None] = mapped_column(Text)
    episode_count: Mapped[int | None] = mapped_column(Integer)
    group_count: Mapped[int | None] = mapped_column(Integer)
    # TMDB's integer enum (1 Original air date, 2 Absolute, 3 DVD, …), passed
    # through rather than interpreted.
    type: Mapped[int | None] = mapped_column(Integer)
    network_id: Mapped[int | None] = mapped_column(ForeignKey(f"{SCHEMA}.network.id"))


class Person(Base):
    """Someone credited on a show or an episode.

    Reached only through credits — TMDB returns a person inline on every cast,
    crew and guest-star entry, so there is no separate person pass to run and no
    `/person/{id}` request in the ingest. That is the whole of ADR-0003 arriving
    for free.

    **Ids are not preserved from TV Maze**, unlike show / season / episode. The
    migration copies the catalog spine because `app` references it (NEU-1042);
    credits are re-ingested from TMDB wholesale, so there is nothing to line up
    and the identity starts at 1. The visible cost is that `/people/{id}` URLs
    change at cutover — no user data points at a person, and nothing links to one
    from outside the show page that produced it.
    """

    __tablename__ = "person"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_person_tmdb_id"),
        {"schema": SCHEMA},
    )
    # `/people?search=` folds both the column and the query token, so the
    # leading-wildcard LIKE needs a GIN trigram index over the folded
    # expression. It is an expression index and cannot be declared here; the
    # migration creates it, mirroring `ix_person_name_folded_trgm` on `tvmaze`.

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    tmdb_id: Mapped[int | None] = mapped_column(Integer)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    original_name: Mapped[str | None] = mapped_column(Text)
    # TMDB's integer enum (0 unknown, 1 female, 2 male, 3 non-binary), passed
    # through rather than interpreted — the same shape `ShowCreator.gender` has.
    # `tvmaze.person.gender` was free text; this is not a port of it.
    gender: Mapped[int | None] = mapped_column(Integer)
    known_for_department: Mapped[str | None] = mapped_column(Text)
    popularity: Mapped[float | None] = mapped_column(Double)
    profile_path: Mapped[str | None] = mapped_column(Text)
    adult: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false"), default=False
    )
    # Deliberately absent, and each absence is a decision rather than an
    # oversight: `country_*`, `timezone`, `birthday` and `deathday` are on
    # `tvmaze.person` because TV Maze's `/people/{id}` returned them. TMDB
    # returns none of them on a credit — they live behind a per-person request
    # the credits ingest does not make — and the audit's person inventory (§5)
    # lists only what a credit carries. Adding them later is a new pass over
    # every credited person, which is exactly the cost the audit priced.


class Character(Base):
    """A role, **interned per show** by `(show_id, name)`.

    TMDB has no character entity: `character` is free text on a credit, so there
    is no `tmdb_id` to conflict on and no upstream identity to preserve. Interning
    is what keeps `CharacterRef` in the API — and therefore the SPA — unchanged
    across the source switch, since the surrogate id survives even though the
    thing behind it narrowed.

    **Narrowing to per-show is the one real model change of NEU-1038** and it was
    measured before it was made: of 1,509,298 characters in prod, 2,621 are played
    by more than one person — every one of them preserved, because recasting and
    voice ensembles happen *within* a show — and exactly **one** spans more than
    one show. Recorded in ADR-0007 and `CONTEXT.md`.

    Same interning pattern as `CrewRole`, one grain finer: a crew role's
    vocabulary is TMDB-wide, a character's is a show's.
    """

    __tablename__ = "character"
    __table_args__ = (
        UniqueConstraint("show_id", "name", name="uq_character_show_name"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(Text, nullable=False)


class CrewRole(Base):
    """An interned `(department, job)` pair — `('Directing', 'Director')`.

    **One lookup, shared by show crew and episode crew**, where `tvmaze` has two.
    That separation is not carried forward, and the reason it existed is the
    reason it cannot be: TV Maze's two vocabularies were genuinely disjoint — 233
    production-function names on the show side against `Writer` / `Director` /
    `Story` / `Teleplay` on the episode side (ADR-0003). TMDB emits the same
    `department` + `job` pair on both sides, and measured
    (`scripts/probe_tmdb_credit_shapes.py`, 5 series, 2026-08-11)
    **all 78 episode-level pairs also appear at show level — 100% overlap**. A
    second lookup would hold a copy of the same vocabulary and turn "every
    Directing credit for this person" into a two-table union.

    Two columns rather than one interned string: `department` is what a person
    page groups by, and it is a closed vocabulary of about a dozen values where
    `job` is a long tail of several hundred.
    """

    __tablename__ = "crew_role"
    __table_args__ = (
        UniqueConstraint("department", "job", name="uq_crew_role_department_job"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    department: Mapped[str] = mapped_column(Text, nullable=False)
    job: Mapped[str] = mapped_column(Text, nullable=False)


class ShowCast(Base):
    """A person playing a character across a show, from `aggregate_credits.cast`.

    One row per *role*, not per person: `aggregate_credits` nests
    `roles: [{credit_id, character, episode_count}]` under one cast entry, so an
    actor who played two characters on one show is two rows here sharing a
    `person_id`.

    **No `UNIQUE (show_id, person_id, character_id)`**, carried forward from
    `tvmaze.show_cast` deliberately. Refresh is delete-then-insert, so there is
    nothing to conflict on, and a uniqueness assumption over upstream data is what
    broke ingestion on `tvmaze.season`. `credit_id` gets no unique key for the
    same reason.
    """

    __tablename__ = "show_cast"
    __table_args__ = (
        # `episode_count` is the sort key (NEU-1039), not `billing_order`: it is
        # the measure `order` only ever proxied for, and it is the one ordering
        # the crew table can share. Postgres scans an index backwards, so
        # ascending serves the descending sort.
        Index("ix_show_cast_show_id_episode_count", "show_id", "episode_count"),
        Index("ix_show_cast_person_id", "person_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    person_id: Mapped[int] = mapped_column(ForeignKey(f"{SCHEMA}.person.id"), nullable=False)
    # Nullable, unlike `tvmaze.show_cast.character_id`. TV Maze always sent a
    # character object; TMDB sends free text that can be empty, and measured it
    # is — rarely, but not never: 1 blank of 7,629 sampled roles
    # (`scripts/probe_tmdb_credit_shapes.py`). NOT NULL would abort a
    # multi-hour pass on that one row, and interning `''` as a character name
    # would invent a role nobody played.
    character_id: Mapped[int | None] = mapped_column(ForeignKey(f"{SCHEMA}.character.id"))
    # TMDB's stable id for this specific credit — the identity free-text
    # character otherwise denies a role. From `roles[].credit_id`.
    credit_id: Mapped[str | None] = mapped_column(Text)
    # Episodes in this role, from `roles[].episode_count`. Strictly better than
    # the billing-order proxy `tvmaze.show_cast.sort_order` stood in for.
    episode_count: Mapped[int | None] = mapped_column(Integer)
    # Episodes for this *person* across the show, summed over their roles by
    # TMDB. Denormalised across a person's rows, which is the grain TMDB gives it.
    total_episode_count: Mapped[int | None] = mapped_column(Integer)
    # Upstream's `order`. Named for the glossary term rather than `tvmaze`'s
    # `sort_order`, which `CONTEXT.md` lists under *Avoid* — the two grains have
    # different orderings and one name for both hid that. Kept because the audit
    # models it and it is the only signal for the top-billed lead of a show whose
    # star appears in fewer episodes than a recurring supporting actor. Nullable,
    # unlike `tvmaze.show_cast.sort_order`: nothing guarantees TMDB sends it.
    billing_order: Mapped[int | None] = mapped_column(Integer)


class ShowCrew(Base):
    """A person's crew role across a show, from `aggregate_credits.crew`.

    One row per job, for the same reason `ShowCast` is one row per role:
    `jobs: [{credit_id, job, episode_count}]` nests under one crew entry.

    **No ordering column at all, and that is measured rather than assumed.** Both
    `tvmaze.show_crew` and `tvmaze.episode_crew` carry a NOT NULL `sort_order`;
    TMDB sends no `order` on a crew entry at all — 0 of 2,066 show-crew and 0 of
    7,456 episode-crew entries sampled
    (`scripts/probe_tmdb_credit_shapes.py`). `episode_count` is the ordering,
    which is what NEU-1039 sorts on.
    """

    __tablename__ = "show_crew"
    __table_args__ = (
        Index("ix_show_crew_show_id_episode_count", "show_id", "episode_count"),
        Index("ix_show_crew_person_id", "person_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    person_id: Mapped[int] = mapped_column(ForeignKey(f"{SCHEMA}.person.id"), nullable=False)
    role_id: Mapped[int] = mapped_column(ForeignKey(f"{SCHEMA}.crew_role.id"), nullable=False)
    credit_id: Mapped[str | None] = mapped_column(Text)
    episode_count: Mapped[int | None] = mapped_column(Integer)
    total_episode_count: Mapped[int | None] = mapped_column(Integer)


class EpisodeGuestCast(Base):
    """A person playing a character in one episode, from `episodes[].guest_stars`.

    The 29-hour `credits_backfill` retires with this table: guest stars ride the
    season request the episodes themselves arrive on, so there is no second pass
    to run (audit §4).

    The uniqueness stays **three-part**, carried forward from
    `uq_egc_episode_person_character`. One character is played by more than one
    person on 17 of 1,043 sampled episodes, so `(episode_id, character_id)` would
    silently drop legitimate rows.
    """

    __tablename__ = "episode_guest_cast"
    __table_args__ = (
        # `NULLS NOT DISTINCT` because `character_id` is nullable here, and under
        # Postgres's default two NULL-character credits for one person on one
        # episode would never conflict — so every re-ingest would add another
        # copy. The same reasoning as `uq_watch_archive_source_row`.
        UniqueConstraint(
            "episode_id",
            "person_id",
            "character_id",
            name="uq_egc_episode_person_character",
            postgresql_nulls_not_distinct=True,
        ),
        # No index on `episode_id` alone: it leads the unique constraint's index,
        # which carries the per-episode lookup. A guest list is a dozen rows, so
        # ordering within one needs no index of its own.
        Index("ix_egc_person_id", "person_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    episode_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.episode.id", ondelete="CASCADE"), nullable=False
    )
    person_id: Mapped[int] = mapped_column(ForeignKey(f"{SCHEMA}.person.id"), nullable=False)
    # Nullable for the same reason as `ShowCast.character_id`. A guest star's
    # character is a character *of the episode's show* — the interning grain is
    # the show, not the episode.
    character_id: Mapped[int | None] = mapped_column(ForeignKey(f"{SCHEMA}.character.id"))
    credit_id: Mapped[str | None] = mapped_column(Text)
    # Upstream's `order`; a guest star entry does carry one, unlike crew. Credit
    # order, not billing order — it is this episode's own credit sequence and
    # means nothing compared across episodes, which is why `CONTEXT.md` keeps the
    # two terms apart and puts `sort order` under *Avoid* for both.
    credit_order: Mapped[int | None] = mapped_column(Integer)


class EpisodeCrew(Base):
    """A person's crew role on one episode, from `episodes[].crew`.

    Points at the same `CrewRole` as `ShowCrew` — see that table for why the
    `tvmaze` split into two lookups does not survive the source change.

    Three-part uniqueness for the same reason as `EpisodeGuestCast`: one person
    holds more than one crew role on 36 of 1,043 sampled episodes. No
    `NULLS NOT DISTINCT` needed here — `role_id` is NOT NULL, because TMDB's
    `department` and `job` are both always present on an episode crew entry.
    """

    __tablename__ = "episode_crew"
    __table_args__ = (
        UniqueConstraint(
            "episode_id", "person_id", "role_id", name="uq_episode_crew_episode_person_role"
        ),
        Index("ix_episode_crew_person_id", "person_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    episode_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.episode.id", ondelete="CASCADE"), nullable=False
    )
    person_id: Mapped[int] = mapped_column(ForeignKey(f"{SCHEMA}.person.id"), nullable=False)
    role_id: Mapped[int] = mapped_column(ForeignKey(f"{SCHEMA}.crew_role.id"), nullable=False)
    credit_id: Mapped[str | None] = mapped_column(Text)


class RateBudget(Base):
    """One upstream's request budget, as a token bucket every process shares.

    An upstream's cap applies to us as a whole. An in-process limiter could
    express that only while every job ran inside the app; the daily now runs as
    its own process (`tvbf.jobs.daily_update`), so the budget has to live
    somewhere both can see (ADR-0006).

    A row per source, unlike `tvmaze.rate_budget`'s single check-constrained
    row: TMDB's ceiling is its own and has nothing to do with TV Maze's
    (NEU-1027). TV Maze keeps its original row until cutover — migrating a live
    token bucket mid-ingest buys nothing.
    """

    __tablename__ = "rate_budget"
    __table_args__ = ({"schema": SCHEMA},)

    source: Mapped[str] = mapped_column(Text, primary_key=True)
    # Fractional by design — refill is `elapsed × rate`, which lands mid-token
    # far more often than not.
    tokens: Mapped[float] = mapped_column(Double, nullable=False)
    # The default only ever stamps a seed row. Every write from the limiter
    # uses `clock_timestamp()`, never `now()`: `now()` is transaction-start
    # time, so an acquirer that waited on the row lock would measure elapsed
    # time from before it waited and over-refill.
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
