"""The source-neutral catalog mirror (ADR-0007), modeled on TMDB's full response surface.

Scope is deliberately **TMDB inward, not TV Maze outward**: every field
NEU-1031's coverage audit classified *modeled* has a column here, whether or not
`tvmaze/models.py` had an ancestor for it. `append_to_response` rides content
ratings, keywords, watch providers, translations and the rest on a request we
already make, so the marginal cost of a field is a column rather than a
multi-hour pass — which is how the TV Maze mirror accumulated four backfills.
See `docs/specs/NEU-1031-tmdb-coverage-audit.md`; every column below traces to a
row in it.

Three conventions hold across the whole schema.

**Surrogate primary key, upstream id alongside.** Every entity carries a
generated `id` and a unique, nullable `tmdb_id` (ADR-0008). `app` references the
surrogate, upserts conflict-target `tmdb_id`, and `tmdb_id IS NULL` means the row
is **locally-authored** — the sanctioned way to hold a show a user tracks that
TMDB does not list. Ingest never deletes or overwrites one.

**Identities are `GENERATED BY DEFAULT`, never `ALWAYS`, and start above TV
Maze's high-water mark.** The migration inserts explicit ids to preserve TV
Maze's, which `ALWAYS` would reject; the sequence starts keep a generated id from
ever landing on one of them. See `_SHOW_ID_START` and friends.

**No `relationship()` declarations.** Nothing navigates via the ORM — it all
reads through `select()` and FK columns. A test fixture inserting a parent and a
child in one `commit()` therefore needs an explicit `await session.flush()`
between them, because the unit of work cannot infer insert order without one.

Credits — person, per-show character, crew role, cast, crew, guest cast — land at
the bottom of this module (NEU-1038). The `created_by` show-creator credit is
*not* among them: TMDB models it separately from crew and so does `ShowCreator`.
"""

from datetime import date, datetime
from decimal import Decimal
from uuid import UUID, uuid4

from sqlalchemy import (
    ARRAY,
    BigInteger,
    Boolean,
    CheckConstraint,
    Computed,
    Date,
    DateTime,
    Double,
    ForeignKey,
    Identity,
    Index,
    Integer,
    Numeric,
    PrimaryKeyConstraint,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from tvbf.db import Base

SCHEMA = "catalog"

# Where the generated identities start.
#
# The migration preserves TV Maze's ids as `catalog.*.id` so `app`'s existing
# rows keep pointing at the right catalog row without being rewritten. Prod's
# maxima are show 93,469 / season 204,038 / episode 3,694,622; starting the
# sequences well clear of those means a generated id can never collide with a
# preserved one, and the gap leaves room for the mirror to have grown between
# now and cutover.
_SHOW_ID_START = 1_000_000
_SEASON_ID_START = 1_000_000
_EPISODE_ID_START = 10_000_000


def _surrogate(start: int = 1) -> Identity:
    """`GENERATED BY DEFAULT AS IDENTITY`, optionally starting past the migrated ids.

    `always=False` is the load-bearing half: the migration supplies explicit ids
    and `GENERATED ALWAYS` would refuse them outright.
    """
    return Identity(always=False, start=start)


class Country(Base):
    """ISO 3166-1 country codes, with TMDB's English name where it gives one.

    Natural key rather than a surrogate, unlike every entity around it: this is a
    static external vocabulary, not a TMDB record — there is no `tmdb_id` to
    conflict on and nothing locally-authored to express. `name` is nullable
    because `origin_country[]` and `content_ratings[]` supply bare codes; only
    `production_countries[]` carries a name.
    """

    __tablename__ = "country"
    __table_args__ = ({"schema": SCHEMA},)

    iso_3166_1: Mapped[str] = mapped_column(Text, primary_key=True)
    name: Mapped[str | None] = mapped_column(Text)


class Language(Base):
    """ISO 639-1 language codes. Natural key, for the same reason as `Country`.

    Populated from `spoken_languages[]`, which is the only place TMDB names a
    language; `languages[]` and `original_language` are bare codes.
    """

    __tablename__ = "language"
    __table_args__ = ({"schema": SCHEMA},)

    iso_639_1: Mapped[str] = mapped_column(Text, primary_key=True)
    english_name: Mapped[str | None] = mapped_column(Text)
    name: Mapped[str | None] = mapped_column(Text)


class Genre(Base):
    __tablename__ = "genre"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_genre_tmdb_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    tmdb_id: Mapped[int | None] = mapped_column(Integer)
    name: Mapped[str] = mapped_column(Text, nullable=False)


class Network(Base):
    """A broadcaster. Absorbs both `tvmaze.network` and `tvmaze.web_channel`.

    TMDB draws no distinction between the two (audit §6), so the browse filter
    reshapes from two lists to one.
    """

    __tablename__ = "network"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_network_tmdb_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    tmdb_id: Mapped[int | None] = mapped_column(Integer)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    logo_path: Mapped[str | None] = mapped_column(Text)
    origin_country: Mapped[str | None] = mapped_column(Text)


class ProductionCompany(Base):
    __tablename__ = "production_company"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_production_company_tmdb_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    tmdb_id: Mapped[int | None] = mapped_column(Integer)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    logo_path: Mapped[str | None] = mapped_column(Text)
    origin_country: Mapped[str | None] = mapped_column(Text)


class Keyword(Base):
    """A discovery tag. Free on the show request; the basis of Discovery and
    Personalized Recommendations, and a multi-hour backfill if skipped."""

    __tablename__ = "keyword"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_keyword_tmdb_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    tmdb_id: Mapped[int | None] = mapped_column(Integer)
    name: Mapped[str] = mapped_column(Text, nullable=False)


class WatchProvider(Base):
    """A streaming service, as named by TMDB's JustWatch partnership.

    **Displaying this data obliges us to attribute JustWatch per media item**, not
    in a sitewide footer, and in addition to TMDB — TMDB staff were asked directly
    and said so, and non-compliance is explicit grounds for revoking API access.
    The obligation attaches to display, not capture, so storing it here is free of
    it; the constraint binds whichever project first puts a provider on screen.
    Recorded on the table so it is inherited rather than rediscovered.
    """

    __tablename__ = "watch_provider"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_watch_provider_tmdb_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    tmdb_id: Mapped[int | None] = mapped_column(Integer)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    logo_path: Mapped[str | None] = mapped_column(Text)
    display_priority: Mapped[int | None] = mapped_column(Integer)


class Show(Base):
    __tablename__ = "show"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_show_tmdb_id"),
        # The migration's mapping tiers look shows up by these two and nothing
        # else (project spec: `/find` by tvdb_id, then imdb_id). Every other
        # external id is stored but never searched.
        Index("ix_show_tvdb_id", "tvdb_id"),
        Index("ix_show_imdb_id", "imdb_id"),
        CheckConstraint(
            "match_method IS NULL OR match_method IN ('tvdb_id', 'imdb_id', 'title_year', 'human')",
            name="ck_show_match_method",
        ),
        # Not for reading — nothing queries a show *by* its last-aired episode.
        # These exist because both columns are `ON DELETE SET NULL` FKs into
        # `catalog.episode`, and Postgres has to find the referencing rows every
        # time an episode is deleted. Unindexed, that is a sequential scan of all
        # 255,010 shows **per deleted episode**: measured against production on
        # 2026-08-11, deleting a single show with 10-40 episodes ran past 60
        # seconds and was still going. With them it is an index lookup.
        #
        # Every other FK into the catalog spine already has a leading index, by
        # accident of being part of a lookup path. These two have no read path, so
        # nothing gave them one — which is exactly why the cost stayed invisible
        # until `show_prune` (NEU-1066) became the first pass to delete episodes
        # in bulk.
        Index("ix_show_last_episode_to_air_id", "last_episode_to_air_id"),
        Index("ix_show_next_episode_to_air_id", "next_episode_to_air_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(_SHOW_ID_START), primary_key=True)
    tmdb_id: Mapped[int | None] = mapped_column(Integer)
    # How the migration arrived at this row's `tmdb_id` (NEU-1043) — one of
    # `tvdb_id` / `imdb_id` / `title_year`, mirroring the three mapping tiers,
    # plus `human` for a row the matching queue resolved by hand (NEU-1044).
    #
    # **The point of it is that two of those tiers are exact and one is not.**
    # A bare `tmdb_id` makes a `/find` hit and a title guess indistinguishable
    # forever; this column is what lets tier 3 be read more sceptically, audited,
    # or retracted as a batch (`WHERE match_method = 'title_year'`) if the
    # go/no-go turns one up wrong.
    #
    # NULL means *this row was not mapped by the migration* — either nothing
    # matched it, or it is a row the TMDB ingest inserted directly, which knows
    # its `tmdb_id` without having had to match anything. It is not a fourth
    # tier, and `tmdb_id IS NULL AND match_method IS NULL` remains the
    # locally-authored row of ADR-0008.
    #
    # `human` says a person decided this row, and `tmdb_id` says what they
    # decided: an id means they confirmed that series, NULL means they looked
    # and found no TMDB counterpart, so the row is locally-authored on purpose
    # rather than by omission. Both are terminal — `human` is the only value
    # this migration's automated passes will never write.
    #
    # Unlike `status`, this vocabulary is ours, so a CHECK constraint is right:
    # a typo'd method is a bug in our own writer rather than an upstream value
    # we do not control.
    match_method: Mapped[str | None] = mapped_column(Text)

    name: Mapped[str] = mapped_column(Text, nullable=False)
    # The untranslated title, in the show's own language. Together with
    # `translation` this *is* the TVBF: Localization project.
    original_name: Mapped[str | None] = mapped_column(Text)
    overview: Mapped[str | None] = mapped_column(Text)
    tagline: Mapped[str | None] = mapped_column(Text)
    homepage: Mapped[str | None] = mapped_column(Text)
    type: Mapped[str | None] = mapped_column(Text)
    adult: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false"), default=False
    )

    # TMDB's string, stored verbatim — `Returning Series` / `Planned` /
    # `In Production` / `Ended` / `Canceled` (audit D1). All five were confirmed
    # against a 1,000-show sweep and no sixth value appeared
    # (`scripts/probe_tmdb_status_vocabulary.py`). Not translated to our old
    # four-value vocabulary: a translation layer would be maintained forever and
    # TMDB's is strictly more informative — `Canceled` is a distinction we cannot
    # currently express at all. No CHECK constraint for the same reason
    # `tvmaze.season` carries no unique key: a vocabulary we do not own is not
    # something to abort an ingest over.
    status: Mapped[str | None] = mapped_column(Text)
    # Generated, not written by ingest — the single piece of status that carries
    # behavior, and the one a straight port gets wrong. Every `status == "Ended"`
    # comparison routes through here instead; without it, canceled shows read as
    # still-running, breaking "finished" for exactly the shows most likely to be
    # finished. Computed in the database so it cannot drift from `status`.
    is_ended: Mapped[bool] = mapped_column(
        Boolean,
        Computed("coalesce(status IN ('Ended', 'Canceled'), false)", persisted=True),
        nullable=False,
    )
    # A genuinely separate boolean per the audit. Measured caveat: across the
    # same 1,000-show sweep it was perfectly determined by `status` (true for
    # Returning Series / In Production / Planned, false for Ended / Canceled), so
    # it carried no information `status` did not. Stored anyway — it rides the
    # same request, and the audit's claim was made about TMDB's model rather than
    # about one sample.
    in_production: Mapped[bool | None] = mapped_column(Boolean)

    # **Dates as a US Eastern viewer saw them**, not raw upstream: TMDB's own
    # values, corrected by `catalog.air_date_offset` where one applies
    # (NEU-1145). `first_air_date` takes **season 1's** offset and
    # `last_air_date` the offset of the season holding the last dated episode,
    # because a show's seasons were not all entered by the same contributor —
    # Ted Lasso's premiere is right and its last-aired date is a day early. See
    # `catalog/offsets.py`, which owns both rules, and `AirDateOffset` below for
    # what the offset means.
    first_air_date: Mapped[date | None] = mapped_column(Date)
    last_air_date: Mapped[date | None] = mapped_column(Date)
    # The uncorrected upstream values, written **only when they differ** from
    # the columns above — so NULL means "no correction was applied and the
    # stored value is TMDB's own", which is true of all but a handful of rows.
    # Same pairing as `Episode.tmdb_air_date`, and it is what makes the
    # correction idempotent; the reasoning is written out there.
    tmdb_first_air_date: Mapped[date | None] = mapped_column(Date)
    tmdb_last_air_date: Mapped[date | None] = mapped_column(Date)

    # The browse `language` filter reads this (audit D3): it is the only one of
    # TMDB's three language concepts with exactly one value per show, which the
    # filter's exact-match semantics require. Note the values change shape — TV
    # Maze stored "English", TMDB stores "en". Not an FK to `language`: that
    # table is populated from `spoken_languages[]`, which need not contain a
    # show's original language, and an FK would make ingest order load-bearing
    # for no gain.
    original_language: Mapped[str | None] = mapped_column(Text)

    popularity: Mapped[float | None] = mapped_column(Double)
    vote_average: Mapped[Decimal | None] = mapped_column(Numeric(5, 3))
    # New at show grain: lets us weight a rating rather than trust a 10.0 from
    # three voters.
    vote_count: Mapped[int | None] = mapped_column(Integer)

    poster_path: Mapped[str | None] = mapped_column(Text)
    backdrop_path: Mapped[str | None] = mapped_column(Text)

    # Both **exclude season 0** — measured, and the same convention D2 adopts for
    # our own completion math.
    number_of_episodes: Mapped[int | None] = mapped_column(Integer)
    number_of_seasons: Mapped[int | None] = mapped_column(Integer)

    # TMDB's own series-level runtime array, stored verbatim, and usually empty:
    # 6 of 7 sampled shows returned `[]` (audit D4).
    episode_run_time: Mapped[list[int] | None] = mapped_column(ARRAY(Integer))
    # The scalar the SPA renders, derived at ingest as the **median of the show's
    # episode runtimes** — populated for 94.9% of episodes, against TMDB's
    # series-level field which is mostly absent. Median rather than mean so a
    # feature-length finale does not drag a 22-minute sitcom upward.
    #
    # **Ordering constraint, not a detail:** this cannot be finalised until every
    # season's episodes are in hand, including `get_tv_season` overflow, and must
    # be recomputed whenever the daily delta adds episodes.
    runtime: Mapped[int | None] = mapped_column(Integer)

    # Denormalised pointers, refreshed by the daily delta. Derivable from the
    # episode rows — but a derivable field still costs a full ~1.5-hour re-ingest
    # to add later, while a nullable FK costs nothing now, and TMDB's answer is
    # authoritative where ours is inference. Treat them as a cache: read a live
    # query where one is available.
    #
    # `use_alter` because show and episode reference each other. Postgres is
    # happy with the cycle; SQLAlchemy's table sort is not, and would refuse to
    # emit `create_all` without it.
    last_episode_to_air_id: Mapped[int | None] = mapped_column(
        ForeignKey(
            f"{SCHEMA}.episode.id",
            ondelete="SET NULL",
            use_alter=True,
            name="fk_show_last_episode_to_air",
        )
    )
    next_episode_to_air_id: Mapped[int | None] = mapped_column(
        ForeignKey(
            f"{SCHEMA}.episode.id",
            ondelete="SET NULL",
            use_alter=True,
            name="fk_show_next_episode_to_air",
        )
    )

    # `external_ids`, flattened onto the row rather than given a 1:1 table — the
    # shape `tvmaze.show.externals_*` already had, and the mapping tiers want
    # `tvdb_id` and `imdb_id` without a join. Measured set, 2026-08-09.
    imdb_id: Mapped[str | None] = mapped_column(Text)
    tvdb_id: Mapped[int | None] = mapped_column(Integer)
    tvrage_id: Mapped[int | None] = mapped_column(Integer)
    wikidata_id: Mapped[str | None] = mapped_column(Text)
    freebase_id: Mapped[str | None] = mapped_column(Text)
    freebase_mid: Mapped[str | None] = mapped_column(Text)
    facebook_id: Mapped[str | None] = mapped_column(Text)
    instagram_id: Mapped[str | None] = mapped_column(Text)
    twitter_id: Mapped[str | None] = mapped_column(Text)

    ingested_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    # When a **complete** TMDB payload was last mirrored onto this row — the
    # full catalog ingest's resumability watermark (NEU-1034), and the same
    # device `tvmaze.show.akas_synced_at` already is.
    #
    # It exists because "already ingested" and "row already present" are
    # different questions here, where under TV Maze they were the same one. The
    # migration copies ~89k shows into this table (NEU-1042) and maps a
    # `tmdb_id` onto most of them (NEU-1043), so those rows exist and are
    # correctly identified while still holding TV Maze data. An ingest resuming
    # on row-existence would skip exactly the shows users track.
    #
    # NULL therefore means *no full TMDB pass has covered this row yet* — true
    # of a copied row, and true of a locally-authored one forever.
    tmdb_synced_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # When this show's **credits** were last written from a complete TMDB payload
    # — the credits backfill's resumability watermark (NEU-1127), stamped
    # alongside `tmdb_synced_at` by `mark_series_synced` because every caller of
    # that fetches `DEFAULT_APPEND`, which carries `aggregate_credits`, and the
    # season blocks that carry `guest_stars` / `crew`.
    #
    # A second column rather than a reuse of `tmdb_synced_at` because the two
    # genuinely disagree on 228,841 production rows: the full ingest ran on
    # 2026-08-10 and the credit writers merged on 2026-08-11, so every one of
    # those shows is fully mirrored and carries no cast, crew or guest cast at
    # all. `tmdb_synced_at IS NOT NULL AND credits_synced_at IS NULL` is exactly
    # that backlog, and it empties as the backfill works through it.
    #
    # NULL therefore means *no pass has written credits onto this row yet*. It
    # does **not** mean the show has none: a show TMDB has no credits for is
    # stamped like any other, which is the whole reason this is a column and not
    # a "has no `show_cast` row" predicate — that predicate cannot tell "we asked
    # and upstream had none" from "we never asked", so it would re-fetch every
    # credit-less show on every run and never converge.
    credits_synced_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # When this show's **recommendations** were last written from a complete TMDB
    # payload — the recommendations backfill's resumability watermark (NEU-1052),
    # stamped alongside the other two by `mark_series_synced` because every
    # caller of that fetches `DEFAULT_APPEND`, which now carries the
    # `recommendations` namespace.
    #
    # A third column for the second reason the second one exists: a "carries no
    # `show_recommendation` row" predicate cannot tell *upstream returned none*
    # from *nobody has asked*, and upstream returning none is ~8% of the
    # zero-vote long tail (project spec §2) — so that predicate would re-fetch
    # every one of them on every run and never converge.
    #
    # NULL therefore means *no pass has written recommendations onto this row*.
    # It does **not** mean the show has none.
    recommendations_synced_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # Set when the show stops appearing in the daily id export, i.e. TMDB has
    # deleted it. The row is never removed: `app.user_show_watch` and
    # `app.user_show_rating` cascade from here, so a delete would destroy user
    # data nothing upstream could restore (ADR-0005). Locally-authored rows are
    # exempt by definition — they were never in the feed.
    deleted_upstream_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class Season(Base):
    __tablename__ = "season"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_season_tmdb_id"),
        Index("ix_season_show_id_number", "show_id", "season_number"),
        {"schema": SCHEMA},
    )
    # **No UNIQUE (show_id, season_number)**, and that is a decision rather than a
    # port. TV Maze reuses a season number within one show on long-running
    # programs that catalogue by calendar year, and a unique key aborts ingestion
    # on exactly those. TMDB was checked for the same quirk and did not show it —
    # 0 of 754 resolved shows had a duplicate `season_number`
    # (`scripts/probe_tmdb_status_vocabulary.py`) — but 754 is a rounding error
    # against TMDB's ~228k TV series, the constraint buys nothing (upserts
    # conflict-target `tmdb_id`, not this pair), and the downside is an integrity
    # error that kills a multi-hour pass on a long-tail show. A plain index
    # carries the lookups instead.

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(_SEASON_ID_START), primary_key=True)
    tmdb_id: Mapped[int | None] = mapped_column(Integer)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    # 0 for specials (audit D2). Not nullable: TMDB always numbers a season.
    season_number: Mapped[int] = mapped_column(Integer, nullable=False)
    name: Mapped[str | None] = mapped_column(Text)
    overview: Mapped[str | None] = mapped_column(Text)
    poster_path: Mapped[str | None] = mapped_column(Text)
    # **The date this season premiered for a US Eastern viewer** — TMDB's own
    # value corrected by this season's `catalog.air_date_offset` row where one
    # applies (NEU-1145). It takes the offset at the same grain the offset is
    # keyed at, so a corrected season premiere can never contradict the
    # corrected date of its own first episode on the page that shows both.
    air_date: Mapped[date | None] = mapped_column(Date)
    # The uncorrected upstream value, written only when it differs. Same pairing
    # as `Episode.tmdb_air_date`, where the reasoning is written out.
    tmdb_air_date: Mapped[date | None] = mapped_column(Date)
    vote_average: Mapped[Decimal | None] = mapped_column(Numeric(5, 3))
    # From `seasons[]` on the series payload, not from the season payload itself.
    episode_count: Mapped[int | None] = mapped_column(Integer)


class Episode(Base):
    __tablename__ = "episode"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_episode_tmdb_id"),
        Index("ix_episode_show_id_season_number", "show_id", "season_number"),
        Index("ix_episode_season_id", "season_id"),
        # Partial, because the predicate it serves is "every row we altered" and
        # that is a rounding error against ~6.5M episodes. It is what makes the
        # verification in NEU-1145 §7 and the whole-feature undo cheap.
        Index(
            "ix_episode_tmdb_air_date_corrected",
            "show_id",
            postgresql_where=text("tmdb_air_date IS NOT NULL"),
        ),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(_EPISODE_ID_START), primary_key=True)
    tmdb_id: Mapped[int | None] = mapped_column(Integer)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    # SET NULL rather than CASCADE, matching `tvmaze.episode`: a season pruned
    # because the payload stopped naming it (ADR-0004) must not take user watch
    # history with it.
    season_id: Mapped[int | None] = mapped_column(
        ForeignKey(f"{SCHEMA}.season.id", ondelete="SET NULL")
    )
    # Denormalised from the season so aired-count and ordering queries need no
    # join — and so the season-0 predicate D2 requires is one column away.
    season_number: Mapped[int] = mapped_column(Integer, nullable=False)
    # Not nullable, unlike `tvmaze.episode.number`. A null number was TV Maze's
    # marker for a special; under TMDB a special is season 0 with a real episode
    # number (audit D2).
    episode_number: Mapped[int] = mapped_column(Integer, nullable=False)
    name: Mapped[str | None] = mapped_column(Text)
    overview: Mapped[str | None] = mapped_column(Text)
    # **The date this episode became available to a US Eastern viewer** — TMDB's
    # own `air_date`, corrected by `catalog.air_date_offset` where one applies
    # (NEU-1145). Not raw upstream, and that is the whole of what this column
    # means differently since that ticket: TMDB carries one contributor-entered
    # calendar date per episode and no regional model at all, so a season whose
    # dates were typed against the US west coast records the Pacific day and
    # reads a day early for everyone else — measured on 198 Apple TV and 93
    # Prime Video rows against TV Maze's pre-cutover snapshot.
    #
    # Read by Upcoming, Watch Next, the aired filter in `episode_repo` and the
    # show / season / episode pages, all of which want the viewer's date.
    #
    # A date and nothing more. TMDB carries no time component, so
    # `tvmaze.episode.airtime` has no counterpart and retires with it (audit §6).
    air_date: Mapped[date | None] = mapped_column(Date)
    # The uncorrected upstream value, written **only when it differs** from
    # `air_date` — so NULL means "no correction was applied and `air_date` is
    # TMDB's own", which is true of essentially every one of the ~6.0M dated
    # rows and keeps the coverage audit's claim literally true for them.
    #
    # It is what makes the correction idempotent rather than a one-way shift.
    # Every writer sets the pair together from the raw value in hand, so
    # `air_date = tmdb_air_date + offset` is the invariant: re-running an ingest
    # cannot double-apply a shift, and a genuine upstream ±1 day change is
    # picked up rather than mistaken for a correction already made — the failure
    # a design that re-applied the offset to whatever it found stored has no way
    # to distinguish. It also makes "every row we altered" an indexed predicate,
    # and un-doing the feature one UPDATE per grain.
    tmdb_air_date: Mapped[date | None] = mapped_column(Date)
    runtime: Mapped[int | None] = mapped_column(Integer)
    still_path: Mapped[str | None] = mapped_column(Text)
    production_code: Mapped[str | None] = mapped_column(Text)
    # `premiere` / `mid_season` / `finale` / `standard`, straight from upstream —
    # finale detection with no heuristic, which is what Push Notifications would
    # otherwise have to invent. No CHECK: the vocabulary is TMDB's, not ours.
    episode_type: Mapped[str | None] = mapped_column(Text)
    vote_average: Mapped[Decimal | None] = mapped_column(Numeric(5, 3))
    vote_count: Mapped[int | None] = mapped_column(Integer)
    # The whole of the `screened_theatrically` namespace, which returns nothing
    # but a list of episodes. A flag is the faithful shape; a table would be a
    # join to store one bit.
    screened_theatrically: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false"), default=False
    )


class AirDateOffset(Base):
    """How many days one season's mirrored airdates are shifted from TMDB's (NEU-1145).

    TMDB models no regional airdate — measured: an episode object carries a
    single `air_date` key, and it is identical under every `language` and
    `region`. What it carries is a calendar date a contributor typed, and for a
    simultaneous global release "the day it came out" has two defensible
    answers: 9pm Pacific Thursday is midnight Eastern Friday. Some seasons were
    entered one way and some the other, which is why the shift splits *within* a
    single show — Ted Lasso's seasons 1-2 agree with the Eastern date and 3-4 do
    not — and why nothing on the show row can predict it. A row here records the
    answer for one season, established against an oracle by
    `tvbf.airdates.reconcile`.

    **Keyed on `(show_id, season_number)`**, the pair `catalog/seasons.py`
    already treats as a season's read-path identity, and deliberately not on
    `season.id`: `episode.season_id` is nullable (`ON DELETE SET NULL`, so a
    pruned season leaves parentless episodes behind), and `catalog.season`
    carries no `UNIQUE (show_id, season_number)`, so a doubled season would make
    an offset keyed on the row ambiguous.

    **A table of its own rather than a column on `catalog.season`**, which is
    what makes "the TMDB ingest never writes an offset, it only reads one"
    structural instead of a rule someone has to remember — the same reasoning
    that keeps `RateBudget` and `IngestRun` in tables of their own.

    `season_number IS NULL` is a show-wide default that any numbered row
    overrides. **The reconciliation job never writes one**; it exists solely as
    an operator escape hatch, which is what keeps the table's two possible
    writers distinguishable by looking at it.
    """

    __tablename__ = "air_date_offset"
    __table_args__ = (
        UniqueConstraint(
            "show_id",
            "season_number",
            name="uq_air_date_offset_show_season",
            # `NULLS NOT DISTINCT` because the show-wide default *is* a NULL
            # `season_number`. Under Postgres's default two of them would never
            # conflict, so an idempotent upsert would insert a second default on
            # every run and the override rule would stop being well defined.
            postgresql_nulls_not_distinct=True,
        ),
        CheckConstraint(
            # **Principled, not defensive.** The disagreement this table is
            # authorised to correct is timezone-shaped, and a timezone artifact
            # can only ever produce ±1 day. Any other delta is a different
            # disagreement — an upstream numbering or scheduling error — and
            # correcting it would make the mirror follow the oracle's schedule
            # rather than fix TMDB's coast, which is scope creep with no bound.
            # The job's trust rule refuses those, and this refuses them again at
            # the one place an operator could enter one by hand.
            "offset_days IN (-1, 1)",
            name="ck_air_date_offset_days",
        ),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    # NULL is the show-wide default — see the class docstring.
    season_number: Mapped[int | None] = mapped_column(Integer)
    # Days to ADD to TMDB's value to get the date a US Eastern viewer saw.
    offset_days: Mapped[int] = mapped_column(Integer, nullable=False)
    # How many episodes the verdict rested on. Evidence rather than bookkeeping:
    # the trust rule requires at least two agreeing episodes, and this is what
    # lets a reader tell an offset established over 2 episodes from one
    # established over 30 without re-running the pass. NULL on a hand-entered
    # row, which is the second way the two writers stay distinguishable.
    episodes_compared: Mapped[int | None] = mapped_column(Integer)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class AirdateShowState(Base):
    """What the airdate pass knows about one show (NEU-1148).

    Today that is the show's id on the oracle, cached so the nightly pass stops
    re-deriving it: `airdates/reconcile` spent two TV Maze requests per show, a
    `/lookup/shows` by external id and then the episode list, and the first of
    those returns the same answer every night. The pass is entirely
    rate-limiter-bound, so halving the requests roughly halves the ~23 minute
    wall clock.

    **Named for what the pass knows, not for the one column it holds.** A
    watermark about our own work — "when did we last reconcile this show?" —
    belongs here too, and would sit oddly under a name about the oracle's
    identity for the show. One table for what the pass knows, not two. NEU-1149
    is the ticket that added it: `last_reconciled_at` is what lets the nightly
    work list ask *is tonight this show's night* rather than re-deriving every
    offset from scratch, and it landed here rather than in a table of its own
    exactly as this paragraph anticipated.

    **A table of its own rather than a column on `catalog.show`**, for the
    reason `AirDateOffset` above is one: ADR-0012 sole-sources the spine from
    TMDB, and a TV Maze id is not TMDB's. `show.tvdb_id` / `show.imdb_id` are
    TMDB's own `external_ids`; this is a sidecar holding a derived integer, and
    that is a different thing from the catalog holding TV Maze rows. It is also
    what gives the negative result a home — a column on `catalog.show` could not
    tell *never asked* from *asked, no counterpart*, and both read NULL.

    **`tvmaze_id IS NULL` means "we looked and TV Maze does not carry it."**
    Without that the ~500 shows in scope with no counterpart would be
    re-looked-up every night forever, which is most of the saving gone. The
    absence of a row is *never asked*, and `resolved_at` — NOT NULL, meaning
    "when we last asked", for both row shapes — is what dates the negative so
    `airdates/show_state.RELOOKUP_MISSING_AFTER` can expire it.

    **No `UNIQUE (tvmaze_id)` and no index on it.** Two of our shows legitimately
    resolving to one TV Maze show is the shape NEU-1146 spent four match tiers
    on — TMDB models the *Will & Grace* revival as a separate series where
    another catalogue keeps it whole — so a unique constraint would fire on
    correct data and, after ten shows in a row, abort the run. Every access is by
    `show_id`, which is the primary key directly: one row per show is the table's
    entire meaning.

    **A pure derived cache.** Nothing here cannot be rebuilt by asking again,
    which is what makes the escape hatch a bare `DELETE FROM
    catalog.airdate_show_state` — see `docs/migration/README.md`.
    """

    __tablename__ = "airdate_show_state"
    __table_args__ = ({"schema": SCHEMA},)

    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), primary_key=True
    )
    # NULL is the negative result, dated by `resolved_at` — see the docstring.
    tvmaze_id: Mapped[int | None] = mapped_column(Integer)
    # When we last asked the oracle about this show, whichever answer it gave.
    resolved_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    # When this show's turn last completed without raising (NEU-1149). NULL is
    # "never done" — the clause that puts a new or newly tracked show on
    # tonight's list. Nullable because NEU-1148's rows predate the column.
    last_reconciled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class ShowGenre(Base):
    __tablename__ = "show_genre"
    __table_args__ = (
        PrimaryKeyConstraint("show_id", "genre_id", name="pk_show_genre"),
        # The PK covers show->genre; browse filters the other way
        # (`genre_id IN (...) GROUP BY show_id`) and needs its own index.
        Index("ix_show_genre_genre_id", "genre_id"),
        {"schema": SCHEMA},
    )

    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    genre_id: Mapped[int] = mapped_column(ForeignKey(f"{SCHEMA}.genre.id"), nullable=False)


class ShowNetwork(Base):
    __tablename__ = "show_network"
    __table_args__ = (
        PrimaryKeyConstraint("show_id", "network_id", name="pk_show_network"),
        Index("ix_show_network_network_id", "network_id"),
        {"schema": SCHEMA},
    )
    # A join table where TV Maze had two scalar FKs. TMDB returns `networks[]`,
    # and a show genuinely can carry more than one.

    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    network_id: Mapped[int] = mapped_column(ForeignKey(f"{SCHEMA}.network.id"), nullable=False)


class SeasonNetwork(Base):
    """`networks` on the season payload — measured, and absent from the ticket's
    season inventory (audit §8). Mirrors the series field at season grain."""

    __tablename__ = "season_network"
    __table_args__ = (
        PrimaryKeyConstraint("season_id", "network_id", name="pk_season_network"),
        Index("ix_season_network_network_id", "network_id"),
        {"schema": SCHEMA},
    )

    season_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.season.id", ondelete="CASCADE"), nullable=False
    )
    network_id: Mapped[int] = mapped_column(ForeignKey(f"{SCHEMA}.network.id"), nullable=False)


class ShowProductionCompany(Base):
    __tablename__ = "show_production_company"
    __table_args__ = (
        PrimaryKeyConstraint("show_id", "company_id", name="pk_show_production_company"),
        Index("ix_show_production_company_company_id", "company_id"),
        {"schema": SCHEMA},
    )

    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    company_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.production_company.id"), nullable=False
    )


class ShowOriginCountry(Base):
    """`origin_country[]` — bare ISO 3166-1 codes."""

    __tablename__ = "show_origin_country"
    __table_args__ = (
        PrimaryKeyConstraint("show_id", "country_code", name="pk_show_origin_country"),
        {"schema": SCHEMA},
    )

    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    country_code: Mapped[str] = mapped_column(
        ForeignKey(f"{SCHEMA}.country.iso_3166_1"), nullable=False
    )


class ShowProductionCountry(Base):
    """`production_countries[]` — the same codes, plus a name `Country` holds."""

    __tablename__ = "show_production_country"
    __table_args__ = (
        PrimaryKeyConstraint("show_id", "country_code", name="pk_show_production_country"),
        {"schema": SCHEMA},
    )

    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    country_code: Mapped[str] = mapped_column(
        ForeignKey(f"{SCHEMA}.country.iso_3166_1"), nullable=False
    )


class ShowLanguage(Base):
    """`languages[]` — the languages a show is available in. Distinct from both
    `original_language` and `spoken_languages[]` (audit D3); Breaking Bad is
    `en` original, `["en","de","es"]` here."""

    __tablename__ = "show_language"
    __table_args__ = (
        PrimaryKeyConstraint("show_id", "language_code", name="pk_show_language"),
        {"schema": SCHEMA},
    )

    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    language_code: Mapped[str] = mapped_column(
        ForeignKey(f"{SCHEMA}.language.iso_639_1"), nullable=False
    )


class ShowSpokenLanguage(Base):
    """`spoken_languages[]` — the languages heard on screen."""

    __tablename__ = "show_spoken_language"
    __table_args__ = (
        PrimaryKeyConstraint("show_id", "language_code", name="pk_show_spoken_language"),
        {"schema": SCHEMA},
    )

    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    language_code: Mapped[str] = mapped_column(
        ForeignKey(f"{SCHEMA}.language.iso_639_1"), nullable=False
    )


class ShowKeyword(Base):
    __tablename__ = "show_keyword"
    __table_args__ = (
        PrimaryKeyConstraint("show_id", "keyword_id", name="pk_show_keyword"),
        Index("ix_show_keyword_keyword_id", "keyword_id"),
        {"schema": SCHEMA},
    )

    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    keyword_id: Mapped[int] = mapped_column(ForeignKey(f"{SCHEMA}.keyword.id"), nullable=False)


class ShowWatchProvider(Base):
    """Where a show can be watched, per country and per kind of offer.

    `link` points at TMDB's own watch page and is denormalised across the offer
    types of one country, because that is the grain the response gives it at and
    the grain a UI needs it at. TMDB deliberately provides no deep links and asks
    that you link there instead.

    See `WatchProvider` for the per-item JustWatch attribution this data carries
    the moment anything displays it.
    """

    __tablename__ = "show_watch_provider"
    __table_args__ = (
        PrimaryKeyConstraint(
            "show_id", "country_code", "offer_type", "provider_id", name="pk_show_watch_provider"
        ),
        Index("ix_show_watch_provider_provider_id", "provider_id"),
        # Our own vocabulary — the keys of the `watch/providers` response — not
        # upstream free text, so a CHECK is safe here where it is not on
        # `show.status`. A new offer kind is a migration, and should be.
        CheckConstraint(
            "offer_type IN ('flatrate', 'buy', 'rent', 'free', 'ads')",
            name="ck_show_watch_provider_offer_type",
        ),
        {"schema": SCHEMA},
    )

    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    country_code: Mapped[str] = mapped_column(
        ForeignKey(f"{SCHEMA}.country.iso_3166_1"), nullable=False
    )
    offer_type: Mapped[str] = mapped_column(Text, nullable=False)
    provider_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.watch_provider.id"), nullable=False
    )
    display_priority: Mapped[int | None] = mapped_column(Integer)
    link: Mapped[str | None] = mapped_column(Text)


class ShowRecommendation(Base):
    """TMDB's "More like this" list for one show, in TMDB's own order (NEU-1052).

    A show-to-show edge with a position, not a lookup: `source_show_id` is the
    show being viewed and `target_show_id` one of the twenty TMDB recommends
    alongside it. `rank` is the position the entry held in the response, so the
    read path is `ORDER BY rank` and nothing has to re-derive an order upstream
    already decided.

    **One endpoint means one provenance, so there is no `source` column**
    (project spec §2). `/similar` was measured and rejected — it returns zero
    for every show `/recommendations` also returns zero for, and noise where it
    answers at all — and a column holding a single constant is a lie waiting for
    a second writer this design says will not come. A later
    "people who watched this also watched" signal is a different table with a
    user dimension, not a second value here.

    **Ranks may have gaps.** A target that does not resolve to a `catalog.show`
    is dropped rather than renumbered, so `rank` keeps meaning *TMDB's position*
    rather than *ours after filtering*. Measured, dropping is a no-op (502 of
    502 sampled targets resolved), and it stays as a guard because a series TMDB
    created this morning is not mirrored until tonight's delta.

    The whole list for a source show is **replaced** on refresh, never merged:
    TMDB's ranking is a total order and a partial update would interleave two
    vintages of it.
    """

    __tablename__ = "show_recommendation"
    __table_args__ = (
        PrimaryKeyConstraint("source_show_id", "rank", name="pk_show_recommendation"),
        # One row per pair, which is what makes "the writer deduplicates" an
        # invariant rather than a habit — TMDB listing a target twice would
        # otherwise store it twice and the read path would show a duplicate card.
        UniqueConstraint("source_show_id", "target_show_id", name="uq_show_recommendation_target"),
        # The PK covers source->target. This is the other direction, and it is
        # not for reading: `target_show_id` is a CASCADE FK into `catalog.show`,
        # and Postgres has to find the referencing rows every time a show is
        # deleted. Unindexed that is a sequential scan of the whole table per
        # deleted show — the cost `ix_show_last_episode_to_air_id` was added for,
        # once `orphan_retire` made bulk show deletion a thing that happens.
        Index("ix_show_recommendation_target_show_id", "target_show_id"),
        {"schema": SCHEMA},
    )

    source_show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    # TMDB's position in the response, 1-based.
    rank: Mapped[int] = mapped_column(Integer, nullable=False)
    target_show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )


class TrendingShow(Base):
    """The current `/trending/tv/week` snapshot — one whole list, replaced daily
    (NEU-1055).

    Trending is the one discovery surface that still calls an endpoint on a
    schedule (project spec §3): it is a velocity signal over view and search
    counts we do not hold, so it cannot be derived locally the way "most
    anticipated" can. One request a day for twenty entries buys it.

    **The table holds exactly one snapshot, not a history.** Every row carries
    the same `captured_at` and a run replaces the lot inside one transaction, so
    a reader sees the previous list or the new one and never a half-written mix.
    A separate header table would normalise the twenty copies of one timestamp
    away and buy nothing: the read path wants "the current list and how old it
    is", which is one query here and a join there.

    **`captured_at` is when the list was fetched, not when it was written.** It
    is what NEU-1056's seven-day staleness cutoff is measured against, and the
    two differ by however long resolution took — small today, and exactly the
    kind of drift that stops being small when a pass grows a retry.

    **Ranks may have gaps**, on `ShowRecommendation`'s precedent: an entry that
    does not resolve to a `catalog.show` is dropped rather than renumbered, so
    `rank` keeps meaning *TMDB's position*. Measured, 20 of 20 trending ids
    resolved — a TMDB spine makes trending the least likely list in the product
    to miss, since these are the most globally popular titles there are — and
    the drop stays as a guard because a series TMDB created this morning is not
    mirrored until tonight's delta.

    `adult` and `deleted_upstream_at` are deliberately **not** filtered on the
    way in. They are read-time filters everywhere else a stored list of shows
    exists (NEU-1053, NEU-1108) for one reason: a list computed in March can
    name a show tombstoned in June, and a write-time copy of the rule would make
    a resurrected show permanently invisible.
    """

    __tablename__ = "trending_show"
    __table_args__ = (
        PrimaryKeyConstraint("rank", name="pk_trending_show"),
        # One row per show, which is what makes "the writer deduplicates" an
        # invariant rather than a habit. It also indexes `show_id`, which the
        # CASCADE below needs: unindexed, every show deletion sequentially scans
        # this table looking for referencing rows.
        UniqueConstraint("show_id", name="uq_trending_show_show"),
        {"schema": SCHEMA},
    )

    # TMDB's position in the response, 1-based.
    rank: Mapped[int] = mapped_column(Integer, nullable=False)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    captured_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class ContentRating(Base):
    """Per-country certification — `TV-MA`, `TV-14`, … . No TV Maze equivalent
    exists, which is why skipping it would be a backfill rather than a gap."""

    __tablename__ = "content_rating"
    __table_args__ = (
        UniqueConstraint("show_id", "country_code", name="uq_content_rating_show_country"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    country_code: Mapped[str] = mapped_column(
        ForeignKey(f"{SCHEMA}.country.iso_3166_1"), nullable=False
    )
    rating: Mapped[str | None] = mapped_column(Text)
    # An unordered bag of advisory labels ("violence", "language"). An array
    # rather than a table: nothing joins on them and they have no identity.
    descriptors: Mapped[list[str] | None] = mapped_column(ARRAY(Text))


class ShowAka(Base):
    """TMDB's `alternative_titles` — an **AKA**, the direct equivalent of
    `tvmaze.show_aka`.

    Named for the glossary term rather than the upstream namespace: `CONTEXT.md`
    fixes "AKA" as the word for this concept across both repos, and a table
    called `alternative_title` would give one concept two names.

    AKA-aware search survives intact — `browse_queries` matches a folded query
    token against the folded title, which the two trigram indexes in the
    migration back. They are expression indexes and cannot be declared here.
    """

    __tablename__ = "show_aka"
    __table_args__ = (
        Index("ix_show_aka_show_id", "show_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    title: Mapped[str] = mapped_column(Text, nullable=False)
    country_code: Mapped[str | None] = mapped_column(Text)
    # TMDB's own free-text note on the kind of title ("Working title", "DVD").
    type: Mapped[str | None] = mapped_column(Text)


class ShowCreator(Base):
    """`created_by[]` — a show-creator credit, which TMDB models separately from
    crew and so do we. A credit type TV Maze never had.

    Self-contained rather than pointing at `catalog.person`, which now exists
    below. Storing the payload as it arrives is the faithful shape: TMDB returns
    `created_by` denormalised, with the person's name, gender and profile path
    inline rather than as a reference, and a creator need not appear in
    `aggregate_credits` at all — so an FK would be a nullable one whose target
    row the credits ingest may never create. `tmdb_person_id` is what resolves to
    a `person_id` for a UI that wants to link the two; adding that column is an
    additive migration whenever something needs it.
    """

    __tablename__ = "show_creator"
    __table_args__ = (
        # `credit_id` is TMDB's stable id for this specific credit. Nullable, so
        # a locally-authored creator conflicts with nothing (NULLS DISTINCT).
        UniqueConstraint("show_id", "credit_id", name="uq_show_creator_show_credit"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    tmdb_person_id: Mapped[int | None] = mapped_column(Integer)
    credit_id: Mapped[str | None] = mapped_column(Text)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    original_name: Mapped[str | None] = mapped_column(Text)
    # TMDB's integer enum (0 unknown, 1 female, 2 male, 3 non-binary), passed
    # through rather than interpreted.
    gender: Mapped[int | None] = mapped_column(Integer)
    profile_path: Mapped[str | None] = mapped_column(Text)


class Translation(Base):
    """Localized `name` / `overview` / `tagline` / `homepage` per locale.

    The TVBF: Localization project *is* this table plus `show.original_name`. A
    locale is a language and a country together — TMDB returns `pt-BR` and
    `pt-PT` separately — so the unique key needs both.
    """

    __tablename__ = "translation"
    __table_args__ = (
        UniqueConstraint(
            "show_id", "language_code", "country_code", name="uq_translation_show_locale"
        ),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    language_code: Mapped[str] = mapped_column(Text, nullable=False)
    country_code: Mapped[str] = mapped_column(Text, nullable=False)
    # How the locale names itself, and its English name — TMDB's `name` and
    # `english_name`, kept distinct from the translated show `name` below.
    language_name: Mapped[str | None] = mapped_column(Text)
    language_english_name: Mapped[str | None] = mapped_column(Text)
    # The `data` object.
    name: Mapped[str | None] = mapped_column(Text)
    overview: Mapped[str | None] = mapped_column(Text)
    tagline: Mapped[str | None] = mapped_column(Text)
    homepage: Mapped[str | None] = mapped_column(Text)


class Image(Base):
    """`images` — backdrops, logos and posters, beyond the one poster and one
    backdrop the series row carries. Public Profiles & Sharing needs them."""

    __tablename__ = "image"
    __table_args__ = (
        UniqueConstraint("show_id", "kind", "file_path", name="uq_image_show_kind_path"),
        # Three keys of one response object, so this vocabulary is ours to
        # enumerate — unlike `show.status`.
        CheckConstraint("kind IN ('backdrop', 'logo', 'poster')", name="ck_image_kind"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    kind: Mapped[str] = mapped_column(Text, nullable=False)
    # TMDB gives images no id; the path is the identity.
    file_path: Mapped[str] = mapped_column(Text, nullable=False)
    aspect_ratio: Mapped[float | None] = mapped_column(Double)
    height: Mapped[int | None] = mapped_column(Integer)
    width: Mapped[int | None] = mapped_column(Integer)
    language_code: Mapped[str | None] = mapped_column(Text)
    vote_average: Mapped[Decimal | None] = mapped_column(Numeric(5, 3))
    vote_count: Mapped[int | None] = mapped_column(Integer)


class Video(Base):
    """`videos` — trailers, teasers, featurettes. Free on the same request."""

    __tablename__ = "video"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_video_tmdb_id"),
        Index("ix_video_show_id", "show_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    # Text, not Integer, unlike every other `tmdb_id` here: TMDB identifies a
    # video by a 24-character hex string. The column keeps the name because the
    # name is the convention — "the upstream key" — and only the type differs.
    tmdb_id: Mapped[str | None] = mapped_column(Text)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    # The id *within* the site — a YouTube watch id, say. Not TMDB's id.
    key: Mapped[str | None] = mapped_column(Text)
    name: Mapped[str | None] = mapped_column(Text)
    site: Mapped[str | None] = mapped_column(Text)
    size: Mapped[int | None] = mapped_column(Integer)
    type: Mapped[str | None] = mapped_column(Text)
    official: Mapped[bool | None] = mapped_column(Boolean)
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    language_code: Mapped[str | None] = mapped_column(Text)
    country_code: Mapped[str | None] = mapped_column(Text)


class EpisodeGroup(Base):
    """`episode_groups` — absolute and DVD orderings, for anime and long-running
    shows.

    Headers only, and deliberately so: the appended namespace returns one row per
    group with its counts, and the groups' actual episode assignments live behind
    a separate `/tv/episode_group/{id}` request that `append_to_response` cannot
    ride. Storing the headers is what the namespace offers; fetching the contents
    is a per-group request some later ordering feature can spend.
    """

    __tablename__ = "episode_group"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_episode_group_tmdb_id"),
        Index("ix_episode_group_show_id", "show_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    # A hex string, like `Video.tmdb_id`.
    tmdb_id: Mapped[str | None] = mapped_column(Text)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str | None] = mapped_column(Text)
    description: Mapped[str | None] = mapped_column(Text)
    episode_count: Mapped[int | None] = mapped_column(Integer)
    group_count: Mapped[int | None] = mapped_column(Integer)
    # TMDB's integer enum (1 Original air date, 2 Absolute, 3 DVD, …), passed
    # through rather than interpreted.
    type: Mapped[int | None] = mapped_column(Integer)
    network_id: Mapped[int | None] = mapped_column(ForeignKey(f"{SCHEMA}.network.id"))


class Person(Base):
    """Someone credited on a show or an episode.

    Reached only through credits — TMDB returns a person inline on every cast,
    crew and guest-star entry, so there is no separate person pass to run and no
    `/person/{id}` request in the ingest. That is the whole of ADR-0003 arriving
    for free.

    **Ids are not preserved from TV Maze**, unlike show / season / episode. The
    migration copies the catalog spine because `app` references it (NEU-1042);
    credits are re-ingested from TMDB wholesale, so there is nothing to line up
    and the identity starts at 1. The visible cost is that `/people/{id}` URLs
    change at cutover — no user data points at a person, and nothing links to one
    from outside the show page that produced it.
    """

    __tablename__ = "person"
    __table_args__ = (
        UniqueConstraint("tmdb_id", name="uq_person_tmdb_id"),
        {"schema": SCHEMA},
    )
    # `/people?search=` folds both the column and the query token, so the
    # leading-wildcard LIKE needs a GIN trigram index over the folded
    # expression. It is an expression index and cannot be declared here; the
    # migration creates it, mirroring `ix_person_name_folded_trgm` on `tvmaze`.

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    tmdb_id: Mapped[int | None] = mapped_column(Integer)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    original_name: Mapped[str | None] = mapped_column(Text)
    # TMDB's integer enum (0 unknown, 1 female, 2 male, 3 non-binary), passed
    # through rather than interpreted — the same shape `ShowCreator.gender` has.
    # `tvmaze.person.gender` was free text; this is not a port of it.
    gender: Mapped[int | None] = mapped_column(Integer)
    known_for_department: Mapped[str | None] = mapped_column(Text)
    popularity: Mapped[float | None] = mapped_column(Double)
    profile_path: Mapped[str | None] = mapped_column(Text)
    adult: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false"), default=False
    )
    # Deliberately absent, and each absence is a decision rather than an
    # oversight: `country_*`, `timezone`, `birthday` and `deathday` are on
    # `tvmaze.person` because TV Maze's `/people/{id}` returned them. TMDB
    # returns none of them on a credit — they live behind a per-person request
    # the credits ingest does not make — and the audit's person inventory (§5)
    # lists only what a credit carries. Adding them later is a new pass over
    # every credited person, which is exactly the cost the audit priced.


class Character(Base):
    """A role, **interned per show** by `(show_id, name)`.

    TMDB has no character entity: `character` is free text on a credit, so there
    is no `tmdb_id` to conflict on and no upstream identity to preserve. Interning
    is what keeps `CharacterRef` in the API — and therefore the SPA — unchanged
    across the source switch, since the surrogate id survives even though the
    thing behind it narrowed.

    **Narrowing to per-show is the one real model change of NEU-1038** and it was
    measured before it was made: of 1,509,298 characters in prod, 2,621 are played
    by more than one person — every one of them preserved, because recasting and
    voice ensembles happen *within* a show — and exactly **one** spans more than
    one show. Recorded in ADR-0007 and `CONTEXT.md`.

    Same interning pattern as `CrewRole`, one grain finer: a crew role's
    vocabulary is TMDB-wide, a character's is a show's.
    """

    __tablename__ = "character"
    __table_args__ = (
        UniqueConstraint("show_id", "name", name="uq_character_show_name"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(Text, nullable=False)


class CrewRole(Base):
    """An interned `(department, job)` pair — `('Directing', 'Director')`.

    **One lookup, shared by show crew and episode crew**, where `tvmaze` has two.
    That separation is not carried forward, and the reason it existed is the
    reason it cannot be: TV Maze's two vocabularies were genuinely disjoint — 233
    production-function names on the show side against `Writer` / `Director` /
    `Story` / `Teleplay` on the episode side (ADR-0003). TMDB emits the same
    `department` + `job` pair on both sides, and measured
    (`scripts/probe_tmdb_credit_shapes.py`, 5 series, 2026-08-11)
    **all 78 episode-level pairs also appear at show level — 100% overlap**. A
    second lookup would hold a copy of the same vocabulary and turn "every
    Directing credit for this person" into a two-table union.

    Two columns rather than one interned string: `department` is what a person
    page groups by, and it is a closed vocabulary of about a dozen values where
    `job` is a long tail of several hundred.
    """

    __tablename__ = "crew_role"
    __table_args__ = (
        UniqueConstraint("department", "job", name="uq_crew_role_department_job"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    department: Mapped[str] = mapped_column(Text, nullable=False)
    job: Mapped[str] = mapped_column(Text, nullable=False)


class ShowCast(Base):
    """A person playing a character across a show, from `aggregate_credits.cast`.

    One row per *role*, not per person: `aggregate_credits` nests
    `roles: [{credit_id, character, episode_count}]` under one cast entry, so an
    actor who played two characters on one show is two rows here sharing a
    `person_id`.

    **No `UNIQUE (show_id, person_id, character_id)`**, carried forward from
    `tvmaze.show_cast` deliberately. Refresh is delete-then-insert, so there is
    nothing to conflict on, and a uniqueness assumption over upstream data is what
    broke ingestion on `tvmaze.season`. `credit_id` gets no unique key for the
    same reason.
    """

    __tablename__ = "show_cast"
    __table_args__ = (
        # `episode_count` is the sort key (NEU-1039), not `billing_order`: it is
        # the measure `order` only ever proxied for, and it is the one ordering
        # the crew table can share. Postgres scans an index backwards, so
        # ascending serves the descending sort.
        Index("ix_show_cast_show_id_episode_count", "show_id", "episode_count"),
        Index("ix_show_cast_person_id", "person_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    person_id: Mapped[int] = mapped_column(ForeignKey(f"{SCHEMA}.person.id"), nullable=False)
    # Nullable, unlike `tvmaze.show_cast.character_id`. TV Maze always sent a
    # character object; TMDB sends free text that can be empty, and measured it
    # is — rarely, but not never: 1 blank of 7,629 sampled roles
    # (`scripts/probe_tmdb_credit_shapes.py`). NOT NULL would abort a
    # multi-hour pass on that one row, and interning `''` as a character name
    # would invent a role nobody played.
    character_id: Mapped[int | None] = mapped_column(ForeignKey(f"{SCHEMA}.character.id"))
    # TMDB's stable id for this specific credit — the identity free-text
    # character otherwise denies a role. From `roles[].credit_id`.
    credit_id: Mapped[str | None] = mapped_column(Text)
    # Episodes in this role, from `roles[].episode_count`. Strictly better than
    # the billing-order proxy `tvmaze.show_cast.sort_order` stood in for.
    episode_count: Mapped[int | None] = mapped_column(Integer)
    # Episodes for this *person* across the show, summed over their roles by
    # TMDB. Denormalised across a person's rows, which is the grain TMDB gives it.
    total_episode_count: Mapped[int | None] = mapped_column(Integer)
    # Upstream's `order`. Named for the glossary term rather than `tvmaze`'s
    # `sort_order`, which `CONTEXT.md` lists under *Avoid* — the two grains have
    # different orderings and one name for both hid that. Kept because the audit
    # models it and it is the only signal for the top-billed lead of a show whose
    # star appears in fewer episodes than a recurring supporting actor. Nullable,
    # unlike `tvmaze.show_cast.sort_order`: nothing guarantees TMDB sends it.
    billing_order: Mapped[int | None] = mapped_column(Integer)


class ShowCrew(Base):
    """A person's crew role across a show, from `aggregate_credits.crew`.

    One row per job, for the same reason `ShowCast` is one row per role:
    `jobs: [{credit_id, job, episode_count}]` nests under one crew entry.

    **No ordering column at all, and that is measured rather than assumed.** Both
    `tvmaze.show_crew` and `tvmaze.episode_crew` carry a NOT NULL `sort_order`;
    TMDB sends no `order` on a crew entry at all — 0 of 2,066 show-crew and 0 of
    7,456 episode-crew entries sampled
    (`scripts/probe_tmdb_credit_shapes.py`). `episode_count` is the ordering,
    which is what NEU-1039 sorts on.
    """

    __tablename__ = "show_crew"
    __table_args__ = (
        Index("ix_show_crew_show_id_episode_count", "show_id", "episode_count"),
        Index("ix_show_crew_person_id", "person_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    show_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.show.id", ondelete="CASCADE"), nullable=False
    )
    person_id: Mapped[int] = mapped_column(ForeignKey(f"{SCHEMA}.person.id"), nullable=False)
    role_id: Mapped[int] = mapped_column(ForeignKey(f"{SCHEMA}.crew_role.id"), nullable=False)
    credit_id: Mapped[str | None] = mapped_column(Text)
    episode_count: Mapped[int | None] = mapped_column(Integer)
    total_episode_count: Mapped[int | None] = mapped_column(Integer)


class EpisodeGuestCast(Base):
    """A person playing a character in one episode, from `episodes[].guest_stars`.

    The 29-hour `credits_backfill` retires with this table: guest stars ride the
    season request the episodes themselves arrive on, so there is no second pass
    to run (audit §4).

    The uniqueness stays **three-part**, carried forward from
    `uq_egc_episode_person_character`. One character is played by more than one
    person on 17 of 1,043 sampled episodes, so `(episode_id, character_id)` would
    silently drop legitimate rows.
    """

    __tablename__ = "episode_guest_cast"
    __table_args__ = (
        # `NULLS NOT DISTINCT` because `character_id` is nullable here, and under
        # Postgres's default two NULL-character credits for one person on one
        # episode would never conflict — so every re-ingest would add another
        # copy. The same reasoning as `uq_watch_archive_source_row`.
        UniqueConstraint(
            "episode_id",
            "person_id",
            "character_id",
            name="uq_egc_episode_person_character",
            postgresql_nulls_not_distinct=True,
        ),
        # No index on `episode_id` alone: it leads the unique constraint's index,
        # which carries the per-episode lookup. A guest list is a dozen rows, so
        # ordering within one needs no index of its own.
        Index("ix_egc_person_id", "person_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    episode_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.episode.id", ondelete="CASCADE"), nullable=False
    )
    person_id: Mapped[int] = mapped_column(ForeignKey(f"{SCHEMA}.person.id"), nullable=False)
    # Nullable for the same reason as `ShowCast.character_id`. A guest star's
    # character is a character *of the episode's show* — the interning grain is
    # the show, not the episode.
    character_id: Mapped[int | None] = mapped_column(ForeignKey(f"{SCHEMA}.character.id"))
    credit_id: Mapped[str | None] = mapped_column(Text)
    # Upstream's `order`; a guest star entry does carry one, unlike crew. Credit
    # order, not billing order — it is this episode's own credit sequence and
    # means nothing compared across episodes, which is why `CONTEXT.md` keeps the
    # two terms apart and puts `sort order` under *Avoid* for both.
    credit_order: Mapped[int | None] = mapped_column(Integer)


class EpisodeCrew(Base):
    """A person's crew role on one episode, from `episodes[].crew`.

    Points at the same `CrewRole` as `ShowCrew` — see that table for why the
    `tvmaze` split into two lookups does not survive the source change.

    Three-part uniqueness for the same reason as `EpisodeGuestCast`: one person
    holds more than one crew role on 36 of 1,043 sampled episodes. No
    `NULLS NOT DISTINCT` needed here — `role_id` is NOT NULL, because TMDB's
    `department` and `job` are both always present on an episode crew entry.
    """

    __tablename__ = "episode_crew"
    __table_args__ = (
        UniqueConstraint(
            "episode_id", "person_id", "role_id", name="uq_episode_crew_episode_person_role"
        ),
        Index("ix_episode_crew_person_id", "person_id"),
        {"schema": SCHEMA},
    )

    id: Mapped[int] = mapped_column(BigInteger, _surrogate(), primary_key=True)
    episode_id: Mapped[int] = mapped_column(
        ForeignKey(f"{SCHEMA}.episode.id", ondelete="CASCADE"), nullable=False
    )
    person_id: Mapped[int] = mapped_column(ForeignKey(f"{SCHEMA}.person.id"), nullable=False)
    role_id: Mapped[int] = mapped_column(ForeignKey(f"{SCHEMA}.crew_role.id"), nullable=False)
    credit_id: Mapped[str | None] = mapped_column(Text)


class IngestRun(Base):
    """One execution of one ingest pass, of any kind.

    Operational metadata rather than catalog data, which is why it sat in
    `tvmaze` right up until NEU-1051 dropped that schema — a second copy would
    have meant a second stale-run cleanup, a second liveness guard and a second
    status route while both spines stood. It moves here rather than to `app`
    because it describes the mirror, the same way `RateBudget` above does, and
    it moved with `ALTER TABLE ... SET SCHEMA` so every historical row came
    with it.
    """

    __tablename__ = "ingest_run"
    __table_args__ = (
        CheckConstraint(
            # The retired TV Maze kinds stay in the vocabulary. Their
            # orchestrators went in NEU-1050 and their schema in NEU-1051, so
            # nothing can write one again — but production rows carrying them
            # travelled here with the table, and a narrower constraint would
            # make history unreadable to buy nothing.
            #
            # `person_initial` is the exception and stays absent, exactly as it
            # was in `tvmaze`: NEU-962 dropped that kind, rows of it still exist
            # (one locally, one cancelled run in prod), and the migration re-adds
            # this constraint NOT VALID so they stay readable while no new one
            # can be written. NOT VALID skips only the scan of existing rows, so
            # writes are enforced either way and what this declaration says is
            # what every database does. Tests build from `create_all` and never
            # see the migration, so they get an ordinary validated constraint
            # from here — and must not seed a `person_initial` row.
            #
            # `catalog_initial` is the TMDB full-catalog ingest (NEU-1034),
            # `catalog_update` its daily delta (NEU-1035), `airdate_reconcile`
            # the nightly airdate pass (NEU-1145) and `trending_snapshot` the
            # daily `/trending/tv/week` capture (NEU-1055) — the only four kinds
            # any live code still writes.
            "kind IN ('initial', 'update', 'akas_backfill', 'ratings_backfill', "
            "'show_refresh', 'person_update', 'episode_credits_backfill', "
            "'catalog_initial', 'catalog_update', 'airdate_reconcile', "
            "'trending_snapshot')",
            name="ck_ingest_run_kind",
        ),
        CheckConstraint(
            "status IN ('running', 'succeeded', 'failed', 'cancelled')",
            name="ck_ingest_run_status",
        ),
        {"schema": SCHEMA},
    )

    id: Mapped[UUID] = mapped_column(PG_UUID(as_uuid=True), primary_key=True, default=uuid4)
    kind: Mapped[str] = mapped_column(String(32), nullable=False)
    status: Mapped[str] = mapped_column(String(16), nullable=False)
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    last_update_cursor: Mapped[int | None] = mapped_column(BigInteger)
    shows_processed: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    shows_failed: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    last_progress_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    error: Mapped[str | None] = mapped_column(Text)


class RateBudget(Base):
    """One upstream's request budget, as a token bucket every process shares.

    An upstream's cap applies to us as a whole. An in-process limiter could
    express that only while every job ran inside the app; a delta now runs as
    its own process (`tvbf.jobs.catalog_update`), so the budget has to live
    somewhere both can see (ADR-0006).

    A row per source, which is what made the next upstream a row rather than
    a rewrite (NEU-1027). The TV Maze bucket it replaced was a single
    check-constrained row in a schema that no longer exists; TMDB is the only
    registered source today, and the keying is the reason that is a fact about
    the registry rather than about this table.
    """

    __tablename__ = "rate_budget"
    __table_args__ = ({"schema": SCHEMA},)

    source: Mapped[str] = mapped_column(Text, primary_key=True)
    # Fractional by design — refill is `elapsed × rate`, which lands mid-token
    # far more often than not.
    tokens: Mapped[float] = mapped_column(Double, nullable=False)
    # The default only ever stamps a seed row. Every write from the limiter
    # uses `clock_timestamp()`, never `now()`: `now()` is transaction-start
    # time, so an acquirer that waited on the row lock would measure elapsed
    # time from before it waited and over-refill.
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
